// ===== Conteúdo educativo e perguntas do quiz =====
// HISTORY, QUIZ_TIPS, QUIZ_ARTICLE, QUIZ_BY_THEME

export const HISTORY = [
  {
    title: "🎈 O Dia da Criança — 1 de Junho",
    text: "O Dia Internacional da Criança celebra-se a 1 de junho em Portugal e em muitos países do mundo. A data foi decidida em 1949 e celebrada pela primeira vez em 1950, para chamar a atenção do mundo para os direitos das crianças. Em Portugal, comemora-se com festas e atividades especiais nas escolas."
  },
  {
    title: "📜 A Declaração dos Direitos da Criança — 1959",
    text: "Em 1959, as Nações Unidas aprovaram a Declaração dos Direitos da Criança, com 10 princípios fundamentais. Reconhecia que todas as crianças têm direito à proteção, à educação, a um nome e a uma nacionalidade — um passo enorme na história da humanidade!"
  },
  {
    title: "🌍 A Convenção dos Direitos da Criança — 1989",
    text: "A 20 de novembro de 1989, as Nações Unidas aprovaram a Convenção sobre os Direitos da Criança — o tratado de direitos humanos mais ratificado da história! Tem 54 artigos e garante a todas as crianças o direito à sobrevivência, ao desenvolvimento, à proteção e à participação."
  },
  {
    title: "⚽ O Direito ao Brincar",
    text: "O artigo 31.º da Convenção garante o direito ao descanso, ao lazer e ao brincar. Brincar não é só divertimento — é essencial para o desenvolvimento do cérebro, da criatividade e das competências sociais das crianças!"
  },
  {
    title: "📚 O Direito à Educação",
    text: "O artigo 28.º da Convenção garante o direito de todas as crianças à educação. Em Portugal, o ensino é obrigatório e gratuito até aos 18 anos. No mundo, ainda há mais de 270 milhões de crianças fora da escola, e a UNICEF trabalha todos os dias para mudar isso."
  },
  {
    title: "💊 O Direito à Saúde",
    text: "O artigo 24.º da Convenção garante o direito de todas as crianças ao mais alto nível de saúde possível. Em Portugal, todas têm acesso ao Serviço Nacional de Saúde e ao Plano Nacional de Vacinação. No mundo, a UNICEF distribui vacinas e água potável para salvar vidas."
  },
  {
    title: "🛡️ O Direito à Proteção",
    text: "Os artigos 19.º e 37.º da Convenção protegem as crianças contra violência, abuso e exploração. Em Portugal, a CPCJ trabalha para proteger crianças em risco. Se uma criança estiver em perigo, pode ligar para a linha SOS Criança: 116 111."
  },
  {
    title: "🗣️ O Direito a Ser Ouvido",
    text: "O artigo 12.º da Convenção garante às crianças o direito de expressar a sua opinião em todas as decisões que as afetam — nas escolas, nas famílias e pelos governos! Em Portugal, existem parlamentos jovens onde podem participar ativamente."
  },
  {
    title: "🌱 O Futuro das Crianças — Os ODS",
    text: "Em 2015, as Nações Unidas aprovaram os 17 Objetivos de Desenvolvimento Sustentável (ODS), a cumprir até 2030. Incluem erradicar a pobreza, garantir saúde e educação de qualidade para todos. As crianças de hoje são os agentes de mudança do futuro!"
  },
  {
    title: "🌟 A UNICEF — A Guardiã dos Direitos",
    text: "A UNICEF foi criada em 1946, após a Segunda Guerra Mundial, para ajudar as crianças afetadas pelo conflito. Hoje trabalha em mais de 190 países. Em Portugal, o Comité Português da UNICEF angaria fundos para programas em todo o mundo!"
  },
  {
    title: "🪪 O Direito à Identidade",
    text: "O artigo 7.º da Convenção garante que toda a criança tem direito a ser registada logo após o nascimento, com um nome e uma nacionalidade. A UNICEF estima que 150 milhões de crianças com menos de 5 anos ainda não têm registo de nascimento. O teu nome é o primeiro direito que recebes!"
  },
  {
    title: "👨‍👩‍👧 O Direito à Família",
    text: "O artigo 9.º da Convenção garante que a criança não deve ser separada dos seus pais, exceto para a sua própria proteção. A família é o primeiro lugar onde a criança aprende amor, segurança e valores."
  },
  {
    title: "✈️ O Direito das Crianças Refugiadas",
    text: "Mais de 43 milhões de crianças estão deslocadas no mundo, fugindo de guerras e violência. O artigo 22.º da Convenção garante que as crianças refugiadas têm exatamente os mesmos direitos que todas as outras. Ser refugiado não apaga os teus direitos!"
  },
  {
    title: "🚫 O Direito a Não Trabalhar em Condições Perigosas",
    text: "O artigo 32.º da Convenção proíbe o trabalho infantil que prejudique a saúde, a segurança ou a educação da criança. Cerca de 138 milhões de crianças ainda estão em trabalho infantil no mundo, mas este número tem vindo a descer. As crianças têm direito a ser crianças!"
  },
  {
    title: "🗣️ O Direito à Liberdade de Expressão",
    text: "O artigo 13.º da Convenção garante que as crianças têm o direito de procurar, receber e partilhar informação e ideias — através de palavras, arte ou escrita. A tua voz importa!"
  },
  {
    title: "🔒 O Direito à Privacidade",
    text: "O artigo 16.º da Convenção protege a vida privada, a família e a correspondência das crianças. Em Portugal, o RGPD dá proteção especial aos dados de menores de 13 anos. Cuida da tua privacidade online — e pede ajuda a um adulto se algo te preocupar!"
  },
  {
    title: "🌍 O Direito à Cultura e à Língua",
    text: "O artigo 30.º da Convenção garante que as crianças de minorias têm o direito de viver segundo a sua cultura e usar a sua língua. No mundo existem cerca de 7 000 línguas vivas — cada uma é um tesouro único da humanidade!"
  },
  {
    title: "♿ O Direito à Inclusão",
    text: "O artigo 23.º da Convenção garante que as crianças com deficiência têm direito a uma vida plena e digna, com acesso à educação e à participação social. A educação inclusiva — em que todas as crianças aprendem juntas — é um direito de todos!"
  },
  {
    title: "🌱 O Direito a um Ambiente Saudável",
    text: "As crianças têm direito a crescer num ambiente limpo e saudável. As alterações climáticas ameaçam este direito: mais de mil milhões de crianças vivem em zonas de risco climático extremo. Separa o lixo, poupa água — o planeta precisa de ti!"
  },
  {
    title: "💻 Os Direitos Digitais das Crianças",
    text: "Em 2021, as Nações Unidas confirmaram que todos os direitos da Convenção se aplicam também ao mundo online — incluindo privacidade e proteção contra o ciberbullying. Em Portugal, a Linha Internet Segura (1800 21 22 23) apoia crianças com problemas online."
  }
];

export const QUIZ_TIPS = {
  historia:     "O Dia da Criança celebra-se a 1 de junho. A Convenção dos Direitos da Criança foi aprovada em 1989.",
  declaracao:   "A Declaração dos Direitos da Criança foi aprovada pelas Nações Unidas em 1959, com 10 princípios.",
  convencao:    "A Convenção sobre os Direitos da Criança de 1989 tem 54 artigos e foi ratificada por quase todos os países.",
  brincar:      "O artigo 31.º da Convenção garante o direito ao brincar, ao descanso e ao lazer.",
  educacao:     "O artigo 28.º garante o direito à educação. Em Portugal é obrigatória até aos 18 anos.",
  saude:        "O artigo 24.º garante o direito à saúde. A UNICEF distribui vacinas e cuidados básicos no mundo.",
  protecao:     "Os artigos 19.º e 37.º protegem as crianças contra violência e exploração. SOS Criança: 116 111.",
  participacao: "O artigo 12.º garante às crianças o direito de serem ouvidas nas decisões que as afetam.",
  futuro:       "Os 17 ODS das Nações Unidas, aprovados em 2015, incluem metas para acabar com a pobreza e garantir educação.",
  unicef:       "A UNICEF foi criada em 1946 e trabalha em mais de 190 países para defender os direitos das crianças.",
  identidade:   "O artigo 7.º garante o direito a um nome e a uma nacionalidade desde o nascimento.",
  familia:      "O artigo 9.º garante que a criança não seja separada dos pais, exceto em situações de proteção.",
  refugiados:   "O artigo 22.º protege as crianças refugiadas com os mesmos direitos das outras crianças.",
  trabalho:     "O artigo 32.º proíbe o trabalho infantil perigoso e prejudicial ao desenvolvimento da criança.",
  expressao:    "O artigo 13.º garante a liberdade de expressão — as crianças podem procurar e partilhar informação.",
  privacidade:  "O artigo 16.º protege a privacidade das crianças — a sua vida pessoal e correspondência.",
  cultura:      "O artigo 30.º garante às crianças de minorias o direito à sua língua, cultura e religião.",
  deficiencia:  "O artigo 23.º garante que as crianças com deficiência têm direito a apoio especial e plena inclusão.",
  ambiente:     "As crianças têm direito a crescer num ambiente saudável — base dos ODS 13, 14 e 15.",
  digital:      "Os direitos digitais das crianças aplicam os artigos da Convenção ao mundo online e às redes sociais."
};

export const QUIZ_ARTICLE = {
  historia:     null,
  declaracao:   null,
  convencao:    null,
  brincar:      "Art. 31.º",
  educacao:     "Art. 28.º",
  saude:        "Art. 24.º",
  protecao:     "Art. 19.º / 37.º",
  participacao: "Art. 12.º",
  futuro:       "ODS 2030",
  unicef:       null,
  identidade:   "Art. 7.º",
  familia:      "Art. 9.º / 10.º",
  refugiados:   "Art. 22.º",
  trabalho:     "Art. 32.º",
  expressao:    "Art. 13.º",
  privacidade:  "Art. 16.º",
  cultura:      "Art. 30.º",
  deficiencia:  "Art. 23.º",
  ambiente:     "ODS 13-15",
  digital:      "Art. 16.º / 17.º"
};

export const QUIZ_BY_THEME = {
  historia: [
    { q:"Em que data se celebra o Dia da Criança em Portugal?", a:[{t:"1 de junho",ok:true},{t:"1 de maio",ok:false},{t:"20 de novembro",ok:false}], exp:"O Dia Internacional da Criança celebra-se a 1 de junho. Esta data foi decidida em novembro de 1949 e celebrada pela primeira vez em 1950. O 20 de novembro é o Dia Universal da Criança, data em que foi aprovada a Convenção dos Direitos da Criança." },
    { q:"Quem escolheu o 1 de junho como Dia da Criança, em 1949?", a:[{t:"A Federação Democrática Internacional das Mulheres",ok:true},{t:"As Nações Unidas",ok:false},{t:"A UNICEF",ok:false}], exp:"A 4 de novembro de 1949, em Moscovo, a Federação Democrática Internacional das Mulheres estabeleceu o 1 de junho como Dia Internacional de Proteção das Crianças. A data começou a ser celebrada a partir de 1950." },
    { q:"Qual é o objetivo do Dia da Criança?", a:[{t:"Celebrar e defender os direitos e o bem-estar das crianças",ok:true},{t:"Assinalar o fim do ano letivo",ok:false},{t:"Comemorar o início do verão",ok:false}], exp:"O Dia da Criança serve para lembrar que todas as crianças têm direitos — à educação, à saúde, ao brincar e à proteção — e que é responsabilidade de todos garantir esses direitos." },
    { q:"Em que ano surgiu o primeiro Dia da Criança?", a:[{t:"1950",ok:true},{t:"1989",ok:false},{t:"1945",ok:false}], exp:"O Dia Internacional da Criança surgiu em 1950, cinco anos após o fim da Segunda Guerra Mundial, num período em que o mundo tentava reconstruir-se e proteger as gerações mais novas." },
    { q:"Em Portugal, o Dia da Criança é celebrado com que tipo de atividades?", a:[{t:"Festas, prendas e atividades especiais nas escolas",ok:true},{t:"Apenas com um feriado nacional",ok:false},{t:"Com uma cerimónia oficial no Parlamento",ok:false}], exp:"Em Portugal, o 1 de junho é celebrado com grande alegria: festas nas escolas, prendas, atividades ao ar livre e ações de sensibilização para os direitos das crianças." }
  ],
  declaracao: [
    { q:"Em que ano foi aprovada a Declaração dos Direitos da Criança?", a:[{t:"1959",ok:true},{t:"1989",ok:false},{t:"1950",ok:false}], exp:"A Declaração dos Direitos da Criança foi aprovada pela Assembleia Geral das Nações Unidas a 20 de novembro de 1959. Trinta anos depois, em 1989, surgiu a Convenção — com força legal obrigatória." },
    { q:"Quantos princípios tinha a Declaração dos Direitos da Criança de 1959?", a:[{t:"10 princípios",ok:true},{t:"54 artigos",ok:false},{t:"7 capítulos",ok:false}], exp:"A Declaração de 1959 tinha 10 princípios fundamentais. Não era juridicamente vinculativa — era uma declaração de intenções. Foi a primeira vez que a comunidade internacional dedicou um documento exclusivamente aos direitos das crianças." },
    { q:"O que reconhecia a Declaração dos Direitos da Criança de 1959?", a:[{t:"Que todas as crianças têm direito à proteção, educação, nome e nacionalidade",ok:true},{t:"Que as crianças devem trabalhar para ajudar as famílias",ok:false},{t:"Que só as crianças de países ricos têm direito à educação",ok:false}], exp:"A Declaração afirmava que todas as crianças, sem discriminação, têm direito à proteção especial, a um nome, a uma nacionalidade, a cuidados de saúde e à educação gratuita." },
    { q:"Qual foi a importância histórica da Declaração de 1959?", a:[{t:"Foi o primeiro documento da ONU dedicado exclusivamente aos direitos das crianças",ok:true},{t:"Foi a primeira lei obrigatória sobre crianças do mundo",ok:false},{t:"Criou a UNICEF",ok:false}], exp:"Antes de 1959, já existia a Declaração de Genebra de 1924 (Liga das Nações), mas a Declaração de 1959 foi o primeiro documento aprovado pelas Nações Unidas exclusivamente sobre direitos da criança, com 10 princípios. Abriu caminho para a Convenção de 1989, com força legal obrigatória." },
    { q:"A Declaração de 1959 era juridicamente obrigatória para os países?", a:[{t:"Não — era uma declaração de intenções, sem força legal",ok:true},{t:"Sim, todos os países eram obrigados a cumpri-la",ok:false},{t:"Sim, mas só para os países fundadores da ONU",ok:false}], exp:"A diferença fundamental entre a Declaração de 1959 e a Convenção de 1989 é que a Declaração era apenas moral — não vinculava juridicamente nenhum Estado. A Convenção de 1989, com 54 artigos, é um tratado internacional com força de lei para os países que a ratificaram." },
    { q:"Que evento histórico motivou maior atenção aos direitos das crianças após 1945?", a:[{t:"A Segunda Guerra Mundial, que deixou milhões de crianças sem lar",ok:true},{t:"A Revolução Industrial, que usou trabalho infantil nas fábricas",ok:false},{t:"A Primeira Guerra Mundial, que criou a Liga das Nações",ok:false}], exp:"O fim da Segunda Guerra Mundial (1945) deixou milhões de crianças deslocadas, órfãs e traumatizadas. Isso impulsionou a criação da UNICEF (1946) e a redação da Declaração dos Direitos da Criança (1959). O sofrimento das crianças durante a guerra tornou urgente a sua proteção legal." }
  ],
  convencao: [
    { q:"Em que data foi aprovada a Convenção sobre os Direitos da Criança?", a:[{t:"20 de novembro de 1989",ok:true},{t:"1 de junho de 1989",ok:false},{t:"20 de novembro de 1959",ok:false}], exp:"A Convenção foi aprovada pela Assembleia Geral da ONU a 20 de novembro de 1989. Por isso, o 20 de novembro é celebrado como o Dia Universal da Criança em todo o mundo." },
    { q:"Em que ano Portugal ratificou a Convenção dos Direitos da Criança?", a:[{t:"1990",ok:true},{t:"1989",ok:false},{t:"1995",ok:false}], exp:"Portugal ratificou a Convenção a 21 de setembro de 1990, apenas alguns meses após a sua aprovação pelas Nações Unidas — um dos primeiros países a fazê-lo." },
    { q:"Quantos artigos tem a Convenção dos Direitos da Criança?", a:[{t:"54 artigos",ok:true},{t:"10 artigos",ok:false},{t:"100 artigos",ok:false}], exp:"A Convenção tem 54 artigos organizados em torno de 4 pilares: sobrevivência, desenvolvimento, proteção e participação. É o tratado de direitos humanos mais ratificado da história." },
    { q:"Quais são os 4 pilares principais da Convenção dos Direitos da Criança?", a:[{t:"Sobrevivência, desenvolvimento, proteção e participação",ok:true},{t:"Educação, saúde, habitação e alimentação",ok:false},{t:"Paz, liberdade, igualdade e fraternidade",ok:false}], exp:"A Convenção organiza-se em torno de 4 princípios fundamentais: o direito à sobrevivência, ao desenvolvimento pleno, à proteção contra abusos e à participação na vida familiar e social." },
    { q:"A Convenção dos Direitos da Criança é o tratado de direitos humanos com mais países a assiná-lo?", a:[{t:"Sim, quase todos os países do mundo a ratificaram",ok:true},{t:"Não, a Declaração Universal dos Direitos Humanos tem mais assinaturas",ok:false},{t:"Não, apenas metade dos países a assinou",ok:false}], exp:"Com 196 países signatários, a Convenção dos Direitos da Criança é o tratado de direitos humanos mais ratificado da história das Nações Unidas." }
  ],
  brincar: [
    { q:"Qual é o artigo da Convenção que garante o direito ao brincar?", a:[{t:"Artigo 31.º",ok:true},{t:"Artigo 24.º",ok:false},{t:"Artigo 12.º",ok:false}], exp:"O artigo 31.º garante o direito de todas as crianças ao descanso, ao lazer, ao brincar e às atividades recreativas adequadas à sua idade." },
    { q:"Por que é que brincar é considerado um direito e não apenas diversão?", a:[{t:"Porque é essencial para o desenvolvimento do cérebro e das competências sociais",ok:true},{t:"Porque as crianças ficam mais calmas",ok:false},{t:"Porque é obrigatório por lei brincar todos os dias",ok:false}], exp:"Brincar é fundamental para o desenvolvimento cognitivo, emocional e social das crianças. Através do jogo, aprendem a comunicar, a resolver problemas, a colaborar e a lidar com as emoções." },
    { q:"O que mostram os estudos sobre crianças que brincam livremente?", a:[{t:"São mais criativas, resilientes e têm melhor saúde mental",ok:true},{t:"Têm piores resultados académicos",ok:false},{t:"São mais difíceis de controlar na escola",ok:false}], exp:"A investigação científica mostra claramente que o brincar livre — sem instruções de adultos — desenvolve a criatividade, a autonomia e a capacidade de gerir emoções e conflitos." },
    { q:"O que mais inclui o direito ao brincar, além do jogo?", a:[{t:"Descanso, lazer e atividades recreativas e culturais",ok:true},{t:"Apenas jogar videojogos",ok:false},{t:"Só atividades desportivas organizadas",ok:false}], exp:"O artigo 31.º é abrangente: inclui o direito ao repouso, às férias escolares, à participação em atividades artísticas e culturais, e ao acesso a espaços de recreio seguros." },
    { q:"Qual das seguintes situações viola o direito ao brincar das crianças?", a:[{t:"Substituir todos os intervalos escolares por estudo",ok:true},{t:"Ter um parque infantil na escola",ok:false},{t:"Ter aulas de música e teatro",ok:false}], exp:"O artigo 31.º protege os intervalos escolares, as férias e o tempo livre das crianças. Sobrecarregar as crianças com trabalho académico sem momentos de brincadeira viola este artigo. A OMS recomenda pelo menos 60 minutos de atividade física diária para crianças em idade escolar." },
    { q:"Em que artigo da Convenção se baseia o direito das crianças a participar em atividades culturais?", a:[{t:"Artigo 31.º — direito ao lazer, jogo e participação cultural",ok:true},{t:"Artigo 17.º — acesso a informação nos media",ok:false},{t:"Artigo 29.º — objetivos da educação",ok:false}], exp:"O artigo 31.º reconhece que as crianças têm direito a participar plenamente na vida cultural e artística. Os Estados devem criar condições — espaços, recursos, programas — que permitam a todas as crianças, independentemente da sua origem, aceder a atividades recreativas e culturais." }
  ],
  educacao: [
    { q:"Qual é o artigo da Convenção que garante o direito à educação?", a:[{t:"Artigo 28.º",ok:true},{t:"Artigo 31.º",ok:false},{t:"Artigo 19.º",ok:false}], exp:"O artigo 28.º da Convenção garante o direito de todas as crianças à educação. O ensino primário deve ser obrigatório e gratuito, e os países devem promover o acesso ao ensino secundário e superior." },
    { q:"Até que idade é o ensino obrigatório em Portugal?", a:[{t:"Até aos 18 anos",ok:true},{t:"Até aos 15 anos",ok:false},{t:"Até aos 12 anos",ok:false}], exp:"Em Portugal, desde 2009, a escolaridade obrigatória foi alargada para 12 anos, o que significa que todas as crianças são obrigadas a estudar até completarem o ensino secundário ou 18 anos." },
    { q:"Quantas crianças ainda estão fora da escola em todo o mundo?", a:[{t:"Mais de 270 milhões de crianças",ok:true},{t:"10 milhões de crianças",ok:false},{t:"50 milhões de crianças",ok:false}], exp:"Segundo dados da UNICEF, mais de 270 milhões de crianças em idade escolar não frequentam a escola. As principais causas são a pobreza, os conflitos armados, a discriminação e a distância das escolas." },
    { q:"O que faz a UNICEF em relação ao direito à educação?", a:[{t:"Trabalha para garantir que todas as crianças do mundo possam estudar",ok:true},{t:"Constrói escolas apenas na Europa",ok:false},{t:"Distribui apenas livros escolares",ok:false}], exp:"A UNICEF trabalha em todo o mundo para garantir acesso à educação, especialmente em zonas de conflito e países em desenvolvimento. Financia escolas, forma professores e apoia programas de inclusão." },
    { q:"O que garante o artigo 29.º da Convenção em relação à educação?", a:[{t:"Que a educação deve desenvolver a personalidade, talentos e respeito pelos outros",ok:true},{t:"Que a educação deve focar-se apenas em matemática e línguas",ok:false},{t:"Que o Estado pode escolher o que as crianças aprendem sem ouvir os pais",ok:false}], exp:"O artigo 29.º vai além do acesso à escola: define os objetivos da educação. A educação deve desenvolver a personalidade da criança, os seus talentos, capacidades mentais e físicas, e preparar a criança para uma vida responsável numa sociedade livre, com respeito pelos direitos humanos." },
    { q:"O que é o ensino inclusivo e como se relaciona com os direitos das crianças?", a:[{t:"É um sistema em que todas as crianças aprendem juntas, independentemente das suas capacidades",ok:true},{t:"É ensino à distância através da internet",ok:false},{t:"É um sistema de escolas privadas acessíveis a todos",ok:false}], exp:"A educação inclusiva, apoiada pelo artigo 23.º (crianças com deficiência) e pelo artigo 28.º (educação para todos), assegura que nenhuma criança é excluída da escola por causa de deficiência, origem étnica, género ou pobreza. Portugal tem avançado significativamente neste modelo desde 2018." }
  ],
  saude: [
    { q:"Qual é o artigo da Convenção que garante o direito à saúde?", a:[{t:"Artigo 24.º",ok:true},{t:"Artigo 31.º",ok:false},{t:"Artigo 28.º",ok:false}], exp:"O artigo 24.º garante que todas as crianças têm direito ao mais alto nível possível de saúde e a serviços médicos. Os países devem combater a mortalidade infantil e garantir cuidados de saúde básicos." },
    { q:"A que serviços de saúde têm acesso as crianças em Portugal?", a:[{t:"Serviço Nacional de Saúde, vacinas e médico de família",ok:true},{t:"Apenas a urgências hospitalares",ok:false},{t:"Só as que têm seguro de saúde privado",ok:false}], exp:"Em Portugal, todas as crianças têm acesso gratuito ao SNS, ao Plano Nacional de Vacinação (que previne doenças como o sarampo e a poliomielite) e a um médico de família no centro de saúde." },
    { q:"O que distribui a UNICEF para ajudar a saúde das crianças no mundo?", a:[{t:"Vacinas, alimentos terapêuticos e água potável",ok:true},{t:"Apenas medicamentos caros",ok:false},{t:"Só equipamento hospitalar sofisticado",ok:false}], exp:"A UNICEF fornece vacinas a metade das crianças do mundo. Também distribui alimentos terapêuticos para crianças com desnutrição severa e apoia sistemas de abastecimento de água potável." },
    { q:"O que é o Plano Nacional de Vacinação (PNV) em Portugal?", a:[{t:"Um programa gratuito de vacinação para todas as crianças portuguesas",ok:true},{t:"Um plano pago apenas para famílias ricas",ok:false},{t:"Um programa só para adultos",ok:false}], exp:"O PNV é gratuito e universal — cobre todas as crianças portuguesas. Previne doenças graves como a tosse convulsa, o sarampo, a hepatite B e a meningite." },
    { q:"Por que morrem ainda muitas crianças de doenças preveníveis no mundo?", a:[{t:"Porque não têm acesso a vacinas, água potável e cuidados básicos",ok:true},{t:"Porque as vacinas não funcionam nesses países",ok:false},{t:"Porque os países não querem aderir à OMS",ok:false}], exp:"A falta de acesso a vacinas, água potável, saneamento básico e cuidados médicos de primeira linha é a principal causa de morte infantil evitável. A UNICEF distribui vacinas a metade das crianças do mundo para combater este problema." },
    { q:"O que significa 'o mais alto nível de saúde possível' no artigo 24.º da Convenção?", a:[{t:"Que cada país deve garantir o melhor cuidado de saúde ao seu alcance para todas as crianças",ok:true},{t:"Que todas as crianças têm direito a hospitais privados",ok:false},{t:"Que a saúde é mais importante do que a educação",ok:false}], exp:"O artigo 24.º reconhece que os recursos de cada país são diferentes — por isso fala em 'o mais alto nível possível'. Mas todos os países devem progressivamente melhorar o acesso das crianças à saúde, nutrição, água potável e ambiente saudável." }
  ],
  protecao: [
    { q:"Quais são os artigos da Convenção que protegem as crianças contra violência e abuso?", a:[{t:"Artigos 19.º e 37.º",ok:true},{t:"Artigos 24.º e 28.º",ok:false},{t:"Artigos 12.º e 31.º",ok:false}], exp:"O artigo 19.º protege as crianças contra todas as formas de violência física e psicológica. O artigo 37.º proíbe a tortura, os tratamentos degradantes e a privação ilegal de liberdade." },
    { q:"Qual é o número da linha de apoio SOS Criança em Portugal?", a:[{t:"116 111",ok:true},{t:"112",ok:false},{t:"800 202 202",ok:false}], exp:"O 116 111 é a linha dedicada às crianças e jovens em perigo em Portugal. Funciona 24 horas por dia, é gratuita e confidencial. Qualquer pessoa pode ligar se souber de uma criança em risco." },
    { q:"O que é a CPCJ?", a:[{t:"Comissão de Proteção de Crianças e Jovens",ok:true},{t:"Centro de Promoção Cultural Juvenil",ok:false},{t:"Comité Português da UNICEF",ok:false}], exp:"A CPCJ é uma instituição oficial portuguesa que intervém para proteger crianças e jovens em risco ou perigo. Existem comissões em todo o país, que trabalham com famílias, escolas e serviços sociais." },
    { q:"O que proibem os artigos de proteção da Convenção dos Direitos da Criança?", a:[{t:"Toda a forma de violência, trabalho perigoso e privação de liberdade",ok:true},{t:"Apenas a violência física",ok:false},{t:"Só o trabalho infantil em fábricas",ok:false}], exp:"A Convenção proíbe todas as formas de maus-tratos (físicos, psicológicos, sexuais), o trabalho infantil perigoso, o tráfico de crianças e qualquer privação ilegal da liberdade." },
    { q:"O que deve fazer uma criança ou adulto que suspeite de maus-tratos a uma criança?", a:[{t:"Contactar a linha 116 111 ou falar com a CPCJ da sua área",ok:true},{t:"Aguardar que a situação se resolva sozinha",ok:false},{t:"Só agir se tiver provas absolutas",ok:false}], exp:"Qualquer pessoa que suspeite de maus-tratos a uma criança pode (e deve) contactar a linha SOS Criança (116 111) ou a CPCJ local. Não são precisas provas absolutas — a suspeita fundamentada é suficiente. Denunciar é proteger." },
    { q:"O que é o tráfico de crianças e como é combatido?", a:[{t:"É a exploração de crianças através de recrutamento e transporte forçados — combatido com leis e cooperação internacional",ok:true},{t:"É apenas o tráfico de drogas envolvendo menores",ok:false},{t:"Só acontece em países em guerra",ok:false}], exp:"O tráfico de crianças inclui o recrutamento, transporte ou acolhimento de menores para fins de exploração sexual, trabalho forçado ou mendicidade. É proibido pelo artigo 35.º da Convenção e combatido pela INTERPOL, EUROPOL e UNICEF." }
  ],
  participacao: [
    { q:"Qual é o artigo da Convenção que garante às crianças o direito a ser ouvidas?", a:[{t:"Artigo 12.º",ok:true},{t:"Artigo 24.º",ok:false},{t:"Artigo 37.º",ok:false}], exp:"O artigo 12.º afirma que as crianças têm o direito de expressar livremente a sua opinião em todas as questões que as afetam. A sua opinião deve ser considerada, tendo em conta a sua idade e maturidade." },
    { q:"Em que espaços podem as crianças em Portugal exercer o direito à participação?", a:[{t:"Nos parlamentos jovens e conselhos municipais de jovens",ok:true},{t:"Apenas no conselho de turma",ok:false},{t:"Só depois dos 18 anos",ok:false}], exp:"Em Portugal, existem parlamentos jovens (assembleias de jovens a nível nacional e regional) e conselhos municipais de jovens, onde crianças e adolescentes podem debater e apresentar propostas." },
    { q:"O direito à participação aplica-se em que contextos?", a:[{t:"Nas escolas, nas famílias e nos governos",ok:true},{t:"Apenas em assembleias internacionais",ok:false},{t:"Só em atividades extracurriculares",ok:false}], exp:"O direito à participação aplica-se em todos os contextos onde se tomam decisões que afetam as crianças: em casa, na escola, nos tribunais, nos serviços sociais e a nível local e nacional." },
    { q:"Por que é importante ouvir a opinião das crianças?", a:[{t:"Porque as decisões que as afetam ficam mais justas e adequadas",ok:true},{t:"Porque as crianças sabem sempre melhor que os adultos",ok:false},{t:"Porque é obrigatório por lei que sejam elas a decidir tudo",ok:false}], exp:"Ouvir as crianças não significa que elas decidem tudo — significa que a sua perspetiva é considerada. Assim, as decisões são mais informadas, mais justas e mais adaptadas às necessidades reais das crianças." },
    { q:"Como se chama o mecanismo da ONU que avalia se os países respeitam a Convenção?", a:[{t:"Comité dos Direitos da Criança das Nações Unidas",ok:true},{t:"Tribunal Internacional de Justiça",ok:false},{t:"Conselho de Segurança da ONU",ok:false}], exp:"O Comité dos Direitos da Criança é um órgão independente de 18 especialistas que analisa os relatórios dos países sobre o cumprimento da Convenção e faz recomendações. Portugal é regularmente avaliado por este Comité." }
  ],
  futuro: [
    { q:"Quantos Objetivos de Desenvolvimento Sustentável (ODS) existem?", a:[{t:"17 objetivos",ok:true},{t:"10 objetivos",ok:false},{t:"27 objetivos",ok:false}], exp:"Em setembro de 2015, os 193 países membros da ONU aprovaram a Agenda 2030 com 17 ODS. Estes objetivos visam erradicar a pobreza, proteger o planeta e garantir prosperidade para todos até 2030." },
    { q:"Em que ano foram aprovados os Objetivos de Desenvolvimento Sustentável?", a:[{t:"2015",ok:true},{t:"2000",ok:false},{t:"2020",ok:false}], exp:"Os 17 ODS foram aprovados na Cimeira das Nações Unidas de setembro de 2015. São para ser atingidos até 2030 e envolvem governos, empresas, organizações e cidadãos de todo o mundo." },
    { q:"Qual ODS se refere diretamente à educação de qualidade?", a:[{t:"ODS 4 — Educação de Qualidade",ok:true},{t:"ODS 1 — Erradicar a Pobreza",ok:false},{t:"ODS 3 — Saúde de Qualidade",ok:false}], exp:"O ODS 4 estabelece o objetivo de garantir educação inclusiva, equitativa e de qualidade para todos até 2030, incluindo o acesso ao ensino pré-escolar e a aprendizagem ao longo da vida." },
    { q:"Por que são as crianças de hoje importantes para o futuro sustentável?", a:[{t:"Porque serão os agentes de mudança que implementarão soluções para os problemas globais",ok:true},{t:"Porque os adultos já não conseguem resolver os problemas do planeta",ok:false},{t:"Porque só as crianças votam nos ODS",ok:false}], exp:"As crianças de hoje crescerão num mundo em transformação e serão os líderes, cientistas, professores e cidadãos que implementarão soluções para as alterações climáticas, a pobreza e a desigualdade." },
    { q:"Qual ODS está diretamente ligado ao fim da pobreza extrema?", a:[{t:"ODS 1 — Erradicar a Pobreza",ok:true},{t:"ODS 8 — Trabalho Digno",ok:false},{t:"ODS 10 — Reduzir as Desigualdades",ok:false}], exp:"O ODS 1 visa erradicar a pobreza extrema para todos os povos até 2030. Cerca de 356 milhões de crianças vivem em pobreza extrema no mundo — menos de 1,90 dólares por dia. Os ODS reconhecem que sem acabar com a pobreza infantil não há futuro sustentável." },
    { q:"O que podem as crianças fazer hoje para contribuir para os ODS?", a:[{t:"Agir no dia a dia: poupar energia, reciclar, respeitar os outros e sensibilizar a comunidade",ok:true},{t:"Nada — os ODS são apenas para governos",ok:false},{t:"Esperar ter 18 anos para começar a participar",ok:false}], exp:"Os ODS são para todos. As crianças contribuem através das suas escolhas diárias, da sua participação na escola e comunidade, da sua voz nas redes sociais e do seu envolvimento em projetos locais. Cada ação conta — por mais pequena que pareça." }
  ],
  unicef: [
    { q:"Em que ano foi criada a UNICEF?", a:[{t:"1946",ok:true},{t:"1959",ok:false},{t:"1989",ok:false}], exp:"A UNICEF foi criada a 11 de dezembro de 1946, pela Assembleia Geral das Nações Unidas, para ajudar as crianças afetadas pela Segunda Guerra Mundial. 'UNICEF' vem de 'United Nations International Children's Emergency Fund'." },
    { q:"Em quantos países trabalha a UNICEF?", a:[{t:"Mais de 190 países e territórios",ok:true},{t:"Apenas 50 países",ok:false},{t:"Só nos países mais ricos",ok:false}], exp:"A UNICEF está presente em mais de 190 países e territórios — ou seja, praticamente em todo o mundo. A sua presença é especialmente importante em zonas de conflito e em países com muita pobreza." },
    { q:"O que significa a sigla UNICEF?", a:[{t:"Fundo das Nações Unidas para a Infância",ok:true},{t:"União Internacional de Crianças e Famílias",ok:false},{t:"Unidade Nacional de Cuidados de Emergência para a Família",ok:false}], exp:"UNICEF vem do inglês 'United Nations Children's Fund' — o nome foi encurtado em 1953, mantendo o acrónimo. Em português, o nome oficial é Fundo das Nações Unidas para a Infância. Foi criada em 1946 como fundo de emergência e é hoje a principal organização mundial dedicada aos direitos das crianças." },
    { q:"O que faz o Comité Português da UNICEF?", a:[{t:"Sensibiliza para os direitos das crianças e angaria fundos para programas no mundo",ok:true},{t:"Gere hospitais pediátricos em Portugal",ok:false},{t:"Substitui o Estado na proteção das crianças portuguesas",ok:false}], exp:"O Comité Português da UNICEF é uma organização não governamental que trabalha em Portugal para consciencializar a sociedade sobre os direitos das crianças e para angariar donativos que financiam programas da UNICEF em todo o mundo." },
    { q:"Qual é um dos principais programas de nutrição da UNICEF para crianças em risco?", a:[{t:"Distribuição de alimentos terapêuticos prontos a usar (RUTF) para desnutrição severa",ok:true},{t:"Vales de desconto em supermercados de países ricos",ok:false},{t:"Distribuição de vitaminas apenas em hospitais privados",ok:false}], exp:"O RUTF (Ready-to-Use Therapeutic Food) é uma pasta nutritiva que a UNICEF distribui em zonas de crise para tratar a desnutrição aguda severa em crianças. É barato, não precisa de refrigeração e salva milhões de vidas por ano." },
    { q:"O 20 de novembro é o Dia Universal da Criança — porquê esta data?", a:[{t:"Porque foi nesse dia de 1989 que a Convenção dos Direitos da Criança foi aprovada",ok:true},{t:"Porque foi o aniversário da fundação da UNICEF",ok:false},{t:"Porque é o dia em que a ONU foi criada",ok:false}], exp:"A 20 de novembro de 1989, a Assembleia Geral das ONU adotou a Convenção sobre os Direitos da Criança. Por isso, esta data é celebrada como Dia Universal da Criança em todo o mundo — um momento para refletir sobre os direitos e o bem-estar das crianças." }
  ],
  identidade: [
    { q:"Qual é o artigo da Convenção que garante o direito a um nome e a uma nacionalidade?", a:[{t:"Artigo 7.º",ok:true},{t:"Artigo 12.º",ok:false},{t:"Artigo 24.º",ok:false}], exp:"O artigo 7.º estipula que toda a criança tem direito a ser registada logo após o nascimento, a ter um nome e a adquirir uma nacionalidade. O registo de nascimento é o primeiro passo para garantir todos os outros direitos." },
    { q:"O que é o registo de nascimento e por que é importante?", a:[{t:"É o documento que prova a existência legal da criança e garante os seus direitos",ok:true},{t:"É apenas uma formalidade sem consequências práticas",ok:false},{t:"Só é obrigatório nos países ricos",ok:false}], exp:"Sem registo de nascimento, uma criança não existe legalmente. Não pode ir à escola, aceder a cuidados de saúde ou ter passaporte. A UNICEF estima que 150 milhões de crianças com menos de 5 anos ainda não estão registadas." },
    { q:"Qual artigo protege a identidade da criança (nome, nacionalidade e relações familiares)?", a:[{t:"Artigo 8.º",ok:true},{t:"Artigo 3.º",ok:false},{t:"Artigo 19.º",ok:false}], exp:"O artigo 8.º obriga os Estados a respeitar e preservar a identidade da criança — o seu nome, nacionalidade e vínculos familiares — e a ajudá-la a recuperar esses elementos se forem ilegalmente retirados." },
    { q:"Quantas crianças no mundo nascem sem registo?", a:[{t:"Cerca de 150 milhões",ok:true},{t:"Menos de 1 milhão",ok:false},{t:"Cerca de 50 milhões",ok:false}], exp:"Segundo a UNICEF, cerca de 150 milhões de crianças menores de 5 anos não têm registo de nascimento, sobretudo na África Subsariana e na Ásia do Sul. Sem registo, ficam invisíveis para o Estado e sem acesso aos seus direitos." },
    { q:"O que é uma criança apátrida?", a:[{t:"Uma criança sem nacionalidade reconhecida por nenhum Estado",ok:true},{t:"Uma criança que perdeu os pais",ok:false},{t:"Uma criança que vive em mais do que um país",ok:false}], exp:"A apatridia ocorre quando uma criança não é reconhecida como nacional por nenhum país. Há cerca de 4 milhões de apátridas no mundo. Sem nacionalidade, ficam excluídas de direitos básicos. A Convenção de 1954 sobre o Estatuto dos Apátridas e o artigo 7.º da CDC protegem estas crianças." },
    { q:"Porque é que algumas crianças não recebem registo de nascimento logo após nascer?", a:[{t:"Por pobreza, distância dos serviços, conflitos armados ou discriminação",ok:true},{t:"Porque os pais preferem esperar até a criança falar",ok:false},{t:"Porque a ONU proibiu o registo em certos países",ok:false}], exp:"As principais barreiras ao registo de nascimento são: distância de serviços de registo civil, pobreza (pagamento de taxas), discriminação de grupos minoritários, e conflitos que destroem infraestruturas administrativas. A UNICEF apoia programas de registo em zonas de crise." }
  ],
  familia: [
    { q:"Qual é o artigo da Convenção que garante que a criança não seja separada dos pais?", a:[{t:"Artigo 9.º",ok:true},{t:"Artigo 7.º",ok:false},{t:"Artigo 31.º",ok:false}], exp:"O artigo 9.º estabelece que a criança não deve ser separada dos pais contra a sua vontade, exceto quando essa separação for necessária para o seu bem-estar — por exemplo, em casos de abuso ou negligência graves." },
    { q:"O que garante o artigo 10.º da Convenção?", a:[{t:"O direito à reunificação familiar quando pais e filhos vivem em países diferentes",ok:true},{t:"O direito a ter sempre dois pais",ok:false},{t:"O direito a escolher com qual dos pais viver",ok:false}], exp:"O artigo 10.º garante que os pedidos de reunificação familiar — quando a criança e os seus pais vivem em países diferentes — sejam tratados de forma positiva, rápida e com humanidade pelos governos." },
    { q:"O que diz o artigo 18.º sobre o papel dos pais?", a:[{t:"Os pais têm responsabilidade conjunta pela criação e desenvolvimento da criança",ok:true},{t:"Só o pai é responsável pela criança",ok:false},{t:"O Estado é o principal responsável pela criação das crianças",ok:false}], exp:"O artigo 18.º reconhece que ambos os pais têm responsabilidades comuns na criação da criança. O Estado deve apoiar os pais nessa tarefa, por exemplo através de serviços de apoio à família e creches." },
    { q:"O que acontece quando a criança não pode viver com a sua família?", a:[{t:"O Estado deve garantir cuidados alternativos adequados, como famílias de acolhimento",ok:true},{t:"A criança fica automaticamente a cargo do Estado sem alternativas",ok:false},{t:"A criança perde os seus direitos enquanto não tiver família",ok:false}], exp:"O artigo 20.º garante que as crianças privadas do ambiente familiar têm direito a proteção e cuidados especiais. As alternativas incluem famílias de acolhimento, kafala (adoção islâmica) ou, em último recurso, instituições adequadas." },
    { q:"O que é a adoção e que artigo da Convenção a regula?", a:[{t:"É um processo legal pelo qual uma criança passa a ser filho de outra família — artigo 21.º",ok:true},{t:"É um acordo informal entre famílias — sem base legal",ok:false},{t:"É proibida pela Convenção dos Direitos da Criança",ok:false}], exp:"O artigo 21.º regula a adoção, garantindo que é feita no superior interesse da criança. A adoção internacional deve respeitar tratados e garantir que a criança não é alvo de tráfico ou lucro indevido." },
    { q:"Qual é o princípio fundamental que deve orientar todas as decisões sobre crianças?", a:[{t:"O superior interesse da criança — artigo 3.º",ok:true},{t:"A vontade dos pais em primeiro lugar",ok:false},{t:"As leis económicas do país em questão",ok:false}], exp:"O artigo 3.º da Convenção estabelece que o superior interesse da criança deve ser a consideração primordial em todas as ações que a afetam — seja por tribunais, serviços sociais, escolas ou pais. É o princípio-mestre da Convenção." }
  ],
  refugiados: [
    { q:"Qual artigo da Convenção protege especificamente as crianças refugiadas?", a:[{t:"Artigo 22.º",ok:true},{t:"Artigo 9.º",ok:false},{t:"Artigo 37.º",ok:false}], exp:"O artigo 22.º estabelece que as crianças que peçam o estatuto de refugiada ou sejam reconhecidas como tal têm direito a proteção especial e ao apoio dos Estados. Têm os mesmos direitos que todas as outras crianças." },
    { q:"Quantas crianças estão deslocadas no mundo devido a conflitos e perseguições?", a:[{t:"Mais de 43 milhões",ok:true},{t:"Menos de 1 milhão",ok:false},{t:"Cerca de 5 milhões",ok:false}], exp:"Segundo dados recentes da UNICEF e ACNUR, mais de 43 milhões de crianças estão deslocadas em todo o mundo — fugindo de guerras, violência, perseguição ou catástrofes naturais. É a maior crise de deslocamento desde a Segunda Guerra Mundial." },
    { q:"O que é o ACNUR?", a:[{t:"A agência das Nações Unidas para os refugiados",ok:true},{t:"Uma organização de países europeus para controlo de fronteiras",ok:false},{t:"Um programa de apoio alimentar da ONU",ok:false}], exp:"O ACNUR (Alto Comissariado das Nações Unidas para os Refugiados) é a agência da ONU responsável por proteger refugiados, apátridas e pessoas deslocadas. Trabalha em mais de 130 países e em parceria com a UNICEF para proteger crianças." },
    { q:"Uma criança refugiada tem os mesmos direitos que as outras crianças?", a:[{t:"Sim, a Convenção aplica-se a todas as crianças sem discriminação",ok:true},{t:"Não, os refugiados têm direitos reduzidos",ok:false},{t:"Só se tiverem documentos de identidade válidos",ok:false}], exp:"O artigo 2.º da Convenção afirma que todos os direitos se aplicam a todas as crianças, sem qualquer discriminação. Ser refugiado, apátrida ou migrante não reduz os direitos de uma criança — pelo contrário, justifica proteção adicional." },
    { q:"O que é uma criança não acompanhada no contexto dos refugiados?", a:[{t:"Uma criança que atravessa fronteiras sem pais ou responsáveis legais",ok:true},{t:"Uma criança que viaja de avião sozinha",ok:false},{t:"Uma criança que não fala a língua do país de acolhimento",ok:false}], exp:"Crianças não acompanhadas ou separadas são especialmente vulneráveis a tráfico, exploração e abuso. O artigo 22.º exige que os Estados lhes concedam a mesma proteção que a outras crianças, incluindo acesso a representação legal e tutores." },
    { q:"Que direitos imediatos deve um país garantir a uma criança refugiada à chegada?", a:[{t:"Abrigo, alimentação, cuidados médicos e acesso à educação",ok:true},{t:"Apenas um visto temporário",ok:false},{t:"Só alojamento em centros de detenção",ok:false}], exp:"Independentemente do estatuto legal, uma criança que chegue como refugiada tem direito imediato a condições de vida dignas, cuidados médicos, proteção contra violência e, o mais depressa possível, acesso à educação — conforme os artigos 22.º, 24.º e 28.º." }
  ],
  trabalho: [
    { q:"Qual é o artigo da Convenção que proíbe o trabalho infantil perigoso?", a:[{t:"Artigo 32.º",ok:true},{t:"Artigo 28.º",ok:false},{t:"Artigo 19.º",ok:false}], exp:"O artigo 32.º protege as crianças contra a exploração económica e contra qualquer trabalho perigoso, que prejudique a sua saúde ou interfira com a sua educação. Os Estados devem fixar idades mínimas de trabalho." },
    { q:"Quantas crianças trabalham em condições de exploração no mundo?", a:[{t:"Cerca de 138 milhões",ok:true},{t:"Menos de 10 milhões",ok:false},{t:"Cerca de 500 milhões",ok:false}], exp:"Segundo a OIT (Organização Internacional do Trabalho), cerca de 138 milhões de crianças estão em situação de trabalho infantil, quase metade em formas perigosas. Este número tem vindo a descer nos últimos anos." },
    { q:"Qual é a idade mínima geral para trabalhar em Portugal?", a:[{t:"16 anos",ok:true},{t:"14 anos",ok:false},{t:"18 anos",ok:false}], exp:"Em Portugal, a idade mínima geral para trabalhar é 16 anos. Menores de 16 anos só podem trabalhar em situações muito específicas (como participar em espetáculos culturais) e com autorização dos pais e autoridades." },
    { q:"O que distingue o trabalho infantil perigoso de uma pequena ajuda em casa?", a:[{t:"O trabalho perigoso prejudica a saúde, a educação e o desenvolvimento da criança",ok:true},{t:"Qualquer trabalho feito por uma criança é automaticamente exploração",ok:false},{t:"Só é ilegal se a criança não receber salário",ok:false}], exp:"A OIT distingue entre trabalho aceitável (pequenas tarefas que não prejudicam o desenvolvimento) e trabalho infantil (que priva a criança da infância, interfere com a escola ou é perigoso para a saúde). O contexto e o impacto são decisivos." },
    { q:"Em que setores é mais comum o trabalho infantil no mundo?", a:[{t:"Agricultura, minas, construção e trabalho doméstico",ok:true},{t:"Apenas nas fábricas têxteis da Ásia",ok:false},{t:"Só em países sem leis laborais",ok:false}], exp:"A maioria do trabalho infantil ocorre na agricultura (61%), seguida de serviços, como trabalho doméstico, e da indústria, incluindo minas e construção. Estas atividades são perigosas para a saúde física e mental das crianças." },
    { q:"Qual organização internacional lidera o combate ao trabalho infantil a nível global?", a:[{t:"OIT — Organização Internacional do Trabalho",ok:true},{t:"INTERPOL",ok:false},{t:"Banco Mundial",ok:false}], exp:"A OIT lidera o programa IPEC (Programa Internacional para a Eliminação do Trabalho Infantil) e define normas internacionais, como a Convenção n.º 182, que proíbe as piores formas de trabalho infantil e foi ratificada por todos os membros da OIT." }
  ],
  expressao: [
    { q:"Qual é o artigo da Convenção que garante a liberdade de expressão?", a:[{t:"Artigo 13.º",ok:true},{t:"Artigo 12.º",ok:false},{t:"Artigo 17.º",ok:false}], exp:"O artigo 13.º garante às crianças o direito de procurar, receber e transmitir informações e ideias — oralmente, por escrito, através da arte ou de qualquer outro meio — desde que não prejudiquem os outros." },
    { q:"O artigo 17.º da Convenção trata de que direito?", a:[{t:"O acesso a informação e meios de comunicação adequados",ok:true},{t:"O direito a ter um telemóvel",ok:false},{t:"O direito a publicar um jornal escolar",ok:false}], exp:"O artigo 17.º reconhece o papel importante dos meios de comunicação e encoraja os Estados a garantir que as crianças tenham acesso a informação de fontes diversas, especialmente material que promova o seu bem-estar social, espiritual e moral." },
    { q:"O direito à liberdade de expressão tem limites?", a:[{t:"Sim, não pode ser usado para prejudicar os direitos e a reputação dos outros",ok:true},{t:"Não, é um direito absoluto sem qualquer restrição",ok:false},{t:"Sim, as crianças só podem expressar-se com autorização dos pais",ok:false}], exp:"O artigo 13.º reconhece que a liberdade de expressão pode ser limitada para respeitar os direitos dos outros ou para proteger a segurança nacional, a ordem pública, a saúde ou a moral. Direitos com responsabilidades." },
    { q:"O que é o bullying e como se relaciona com os direitos das crianças?", a:[{t:"É uma violação dos direitos da criança — prejudica a dignidade, a saúde e a educação",ok:true},{t:"É um problema menor que as crianças devem resolver sozinhas",ok:false},{t:"Só é relevante para os direitos se causar danos físicos",ok:false}], exp:"O bullying — seja físico, verbal ou online (ciberbullying) — viola vários artigos da Convenção: o direito à dignidade (art. 16.º), à proteção (art. 19.º) e à saúde (art. 24.º). As escolas e os Estados têm obrigação de prevenir e combater o bullying." },
    { q:"O que é a liberdade de pensamento e consciência das crianças? (art. 14.º)", a:[{t:"O direito a formar e expressar as suas próprias crenças e opiniões",ok:true},{t:"O direito a nunca frequentar aulas de religião",ok:false},{t:"O direito a não obedecer a regras escolares",ok:false}], exp:"O artigo 14.º garante que as crianças têm o direito à liberdade de pensamento, consciência e religião. Os pais têm o direito de orientar a criança nesta matéria, de forma compatível com os interesses superiores da criança e com a sua autonomia crescente." },
    { q:"Como pode uma criança exercer o direito à expressão na escola?", a:[{t:"Participando em assembleias de turma, jornais escolares e projetos artísticos",ok:true},{t:"Apenas nos testes e fichas de avaliação",ok:false},{t:"Só se tiver autorização escrita dos pais",ok:false}], exp:"As escolas são espaços privilegiados para o exercício da expressão: assembleias de turma, conselhos de alunos, jornais escolares, teatro, música e projetos de cidadania são exemplos concretos do artigo 13.º em ação no quotidiano escolar." }
  ],
  privacidade: [
    { q:"Qual é o artigo da Convenção que protege a privacidade das crianças?", a:[{t:"Artigo 16.º",ok:true},{t:"Artigo 8.º",ok:false},{t:"Artigo 13.º",ok:false}], exp:"O artigo 16.º garante que nenhuma criança seja sujeita a interferências arbitrárias na sua vida privada, família, domicílio ou correspondência, nem a ataques à sua honra e reputação. As crianças têm direito à proteção da lei contra tais ataques." },
    { q:"O que é o RGPD e como protege as crianças?", a:[{t:"É o regulamento europeu de proteção de dados, que dá proteção especial aos dados de crianças",ok:true},{t:"É uma lei apenas para adultos",ok:false},{t:"É um sistema de controlo parental obrigatório",ok:false}], exp:"O Regulamento Geral de Proteção de Dados (RGPD) da União Europeia, em vigor desde 2018, dá proteção especial aos dados pessoais das crianças. Em Portugal, o consentimento para usar dados de menores de 13 anos deve ser dado pelos pais." },
    { q:"As fotografias de crianças partilhadas sem autorização nas redes sociais violam algum direito?", a:[{t:"Sim, violam o direito à privacidade e à imagem da criança",ok:true},{t:"Não, qualquer pessoa pode partilhar fotos de crianças livremente",ok:false},{t:"Só é ilegal se a foto for em ambiente escolar",ok:false}], exp:"Partilhar fotos de crianças sem consentimento — mesmo de familiares — pode violar o direito à privacidade (art. 16.º) e à proteção da imagem. Em Portugal, a publicação de imagens de menores sem autorização pode ser ilegal, especialmente em contextos que os identifiquem." },
    { q:"O que devem as crianças fazer se sentirem que a sua privacidade está a ser violada online?", a:[{t:"Falar com um adulto de confiança e denunciar às plataformas ou autoridades",ok:true},{t:"Ignorar porque a internet não tem regras",ok:false},{t:"Responder ao agressor diretamente",ok:false}], exp:"As crianças devem falar com um adulto de confiança (pais, professor, psicólogo) e denunciar às plataformas digitais. Em Portugal, a Linha Internet Segura (1800 21 22 23) apoia crianças vítimas de violações de privacidade e outros problemas online." },
    { q:"O que é o 'direito ao esquecimento' e como beneficia as crianças?", a:[{t:"O direito de pedir a remoção de informação pessoal online que já não é relevante",ok:true},{t:"O direito de não ser avaliado na escola",ok:false},{t:"O direito de apagar as notas negativas do boletim escolar",ok:false}], exp:"O 'direito ao esquecimento' (RGPD, art. 17.º) permite pedir às plataformas digitais que apaguem dados pessoais. É especialmente importante para os jovens: publicações constrangedoras de infância não devem persegui-los na vida adulta." },
    { q:"O que é o 'sharenting' e que riscos apresenta?", a:[{t:"É a partilha excessiva de fotos e dados de filhos pelos pais nas redes sociais",ok:true},{t:"É um tipo de bullying online entre crianças",ok:false},{t:"É um sistema de controlo parental digital",ok:false}], exp:"'Sharenting' (share + parenting) é a prática de pais partilharem publicações frequentes sobre os filhos online. Pode violar a privacidade da criança, criar uma 'pegada digital' sem consentimento e expô-la a riscos. O artigo 16.º da CDC protege as crianças destas situações." }
  ],
  cultura: [
    { q:"Qual artigo garante às crianças de minorias o direito à sua língua e cultura?", a:[{t:"Artigo 30.º",ok:true},{t:"Artigo 17.º",ok:false},{t:"Artigo 28.º",ok:false}], exp:"O artigo 30.º estabelece que as crianças pertencentes a minorias étnicas, religiosas ou linguísticas não podem ser privadas do direito de ter a sua própria vida cultural, de professar e praticar a sua religião ou de usar a sua língua." },
    { q:"O que é a diversidade cultural e por que é importante respeitar?", a:[{t:"É a variedade de culturas, línguas e tradições no mundo — enriquece a humanidade",ok:true},{t:"É um problema que dificulta a convivência entre povos",ok:false},{t:"Só é relevante fora de Portugal",ok:false}], exp:"A diversidade cultural é uma riqueza da humanidade. A UNESCO defende que todas as culturas têm o mesmo valor e merecem proteção. Em Portugal, vivem pessoas de mais de 180 nacionalidades, tornando o país culturalmente muito diverso." },
    { q:"Quantas línguas são faladas no mundo atualmente?", a:[{t:"Cerca de 7 000 línguas",ok:true},{t:"Cerca de 200 línguas",ok:false},{t:"Cerca de 1 000 línguas",ok:false}], exp:"Estima-se que existam cerca de 7 000 línguas vivas no mundo. Muitas estão em risco de extinção — quando uma língua morre, perde-se também uma forma única de ver e descrever o mundo. Preservar as línguas minoritárias é proteger a diversidade cultural." },
    { q:"Em Portugal, que língua além do Português tem estatuto oficial de língua regional?", a:[{t:"O Mirandês, falado em Miranda do Douro",ok:true},{t:"O Galego, falado no Norte",ok:false},{t:"O Crioulo, falado em Lisboa",ok:false}], exp:"O Mirandês é a única língua regional com reconhecimento oficial em Portugal, falada em Miranda do Douro e arredores. Tem raízes na antiga língua asturo-leonesa e é património linguístico único. A sua proteção é um exemplo do artigo 30.º em ação." },
    { q:"O que é a UNESCO e que papel tem na proteção das culturas?", a:[{t:"É a agência da ONU para a educação, ciência e cultura — protege o património cultural mundial",ok:true},{t:"É uma organização de países ricos para financiar museus",ok:false},{t:"É o serviço secreto cultural da União Europeia",ok:false}], exp:"A UNESCO (United Nations Educational, Scientific and Cultural Organization) promove a paz através da educação, ciência e cultura. Gere a Lista do Património Mundial e a Convenção para a Salvaguarda do Património Imaterial, protegendo tradições, línguas e expressões culturais." },
    { q:"Porque é importante que as crianças conheçam a cultura dos outros?", a:[{t:"Para desenvolver empatia, respeito e competências para viver num mundo diverso",ok:true},{t:"Para poder criticar melhor as outras culturas",ok:false},{t:"Porque a lei obriga ao estudo de todas as culturas",ok:false}], exp:"O contacto com outras culturas desde cedo desenvolve a empatia, combate preconceitos e prepara as crianças para uma cidadania global. O artigo 29.º da CDC destaca o desenvolvimento do respeito pelas outras culturas como objetivo central da educação." }
  ],
  deficiencia: [
    { q:"Qual artigo da Convenção protege as crianças com deficiência?", a:[{t:"Artigo 23.º",ok:true},{t:"Artigo 24.º",ok:false},{t:"Artigo 28.º",ok:false}], exp:"O artigo 23.º reconhece que as crianças com deficiência têm direito a uma vida plena e digna, em condições que garantam a sua participação ativa na sociedade. Os Estados devem assegurar apoio especial e inclusão." },
    { q:"O que é a educação inclusiva?", a:[{t:"Um sistema em que todas as crianças, com ou sem deficiência, aprendem juntas",ok:true},{t:"Um sistema de escolas separadas para crianças com necessidades especiais",ok:false},{t:"Aulas online para crianças com mobilidade reduzida",ok:false}], exp:"A educação inclusiva pressupõe que todas as crianças aprendam juntas, com as adaptações necessárias para cada uma. Portugal tem avançado neste modelo, integrando alunos com necessidades educativas especiais nas escolas regulares com apoio especializado." },
    { q:"Qual a percentagem estimada de crianças no mundo com algum tipo de deficiência?", a:[{t:"Cerca de 15%",ok:true},{t:"Menos de 1%",ok:false},{t:"Mais de 50%",ok:false}], exp:"A OMS estima que cerca de 15% da população mundial vive com alguma forma de deficiência. No caso das crianças, estima-se que entre 93 e 150 milhões enfrentam alguma deficiência. Muitas enfrentam barreiras no acesso à educação, saúde e participação social." },
    { q:"O que são tecnologias de apoio e como ajudam as crianças com deficiência?", a:[{t:"São ferramentas que compensam limitações e aumentam a autonomia e participação",ok:true},{t:"São medicamentos especiais para crianças com deficiência",ok:false},{t:"São apenas cadeiras de rodas e bengalas",ok:false}], exp:"Tecnologias de apoio incluem software de leitura de ecrã, comunicadores alternativos, impressoras Braille, aplicações de comunicação aumentativa e muitas outras ferramentas. Permitem que crianças com deficiências físicas, sensoriais ou cognitivas participem plenamente na escola e na sociedade." },
    { q:"O que é a acessibilidade e por que é um direito das crianças com deficiência?", a:[{t:"É a garantia de que espaços, serviços e informação são utilizáveis por todos",ok:true},{t:"É um benefício opcional que os países podem oferecer",ok:false},{t:"É apenas sobre rampas para cadeiras de rodas",ok:false}], exp:"A acessibilidade — física, digital e comunicacional — é uma condição para que as crianças com deficiência possam exercer os seus direitos. A Convenção da ONU sobre os Direitos das Pessoas com Deficiência (2006) e o artigo 23.º da CDC exigem que os Estados removam barreiras e garantam plena participação." },
    { q:"O que significa o slogan 'Nada sobre nós sem nós' no contexto das crianças com deficiência?", a:[{t:"Que as decisões que as afetam devem contar com a sua participação",ok:true},{t:"Que as crianças com deficiência devem viver de forma completamente independente",ok:false},{t:"Que os pais não devem participar nas decisões sobre os filhos",ok:false}], exp:"'Nada sobre nós sem nós' é o lema do movimento de defesa dos direitos das pessoas com deficiência. Significa que qualquer política, lei ou serviço que afete crianças com deficiência deve ser desenvolvido com a sua participação ativa. O artigo 12.º da CDC e o artigo 23.º reforçam este princípio." }
  ],
  ambiente: [
    { q:"Existe um artigo específico sobre o direito ao ambiente na Convenção de 1989?", a:[{t:"Não diretamente, mas os ODS e comentários gerais reconhecem este direito",ok:true},{t:"Sim, é o artigo 29.º",ok:false},{t:"Sim, foi acrescentado em 2010",ok:false}], exp:"A Convenção de 1989 não tem um artigo específico sobre ambiente, mas o Comité dos Direitos da Criança reconhece nos seus comentários gerais que as alterações climáticas e a degradação ambiental ameaçam todos os direitos das crianças. Os ODS 13, 14 e 15 abordam estes temas." },
    { q:"Como afetam as alterações climáticas os direitos das crianças?", a:[{t:"Ameaçam o direito à saúde, à alimentação, à água e a um futuro seguro",ok:true},{t:"Não afetam significativamente as crianças",ok:false},{t:"Só afetam crianças que vivem em zonas costeiras",ok:false}], exp:"As alterações climáticas afetam desproporcionalmente as crianças: aumentam doenças respiratórias, reduzem o acesso a água potável e alimentos, causam deslocamentos forçados e comprometem o seu direito a um futuro seguro. A UNICEF alerta que mais de mil milhões de crianças vivem em zonas de risco extremo." },
    { q:"O que pode cada criança fazer para ajudar o ambiente?", a:[{t:"Reduzir desperdícios, poupar energia, plantar árvores e sensibilizar outros",ok:true},{t:"Nada — só os governos e empresas podem fazer diferença",ok:false},{t:"Deixar de ir à escola para protestar",ok:false}], exp:"Cada criança pode contribuir: separar o lixo, poupar água e energia, escolher produtos sustentáveis, plantar plantas, comer menos carne e sensibilizar família e amigos. As pequenas ações individuais, multiplicadas por milhões, fazem diferença." },
    { q:"O que significa a sigla ODS?", a:[{t:"Objetivos de Desenvolvimento Sustentável",ok:true},{t:"Organização dos Direitos Sociais",ok:false},{t:"Ordem de Defesa da Sustentabilidade",ok:false}], exp:"Os ODS (Objetivos de Desenvolvimento Sustentável) são 17 metas aprovadas pelas Nações Unidas em 2015 para tornar o mundo melhor até 2030. Os ODS 13 (Ação Climática), 14 (Vida Marinha) e 15 (Vida Terrestre) protegem diretamente o ambiente onde as crianças crescem." },
    { q:"O que é a 'pegada ecológica'?", a:[{t:"A quantidade de recursos naturais que cada pessoa consome",ok:true},{t:"O rasto de sujidade que deixamos no chão",ok:false},{t:"O número de animais que existem numa floresta",ok:false}], exp:"A pegada ecológica mede os recursos naturais (água, terra, energia) que cada pessoa usa. Se toda a humanidade vivesse como um europeu médio, precisaríamos de 3 planetas! Reduzir a nossa pegada — consumindo menos, reciclando e poupando energia — é essencial para preservar o planeta para as gerações futuras." },
    { q:"Qual é o principal gás responsável pelo aquecimento global?", a:[{t:"O dióxido de carbono (CO₂)",ok:true},{t:"O oxigénio (O₂)",ok:false},{t:"O azoto (N₂)",ok:false}], exp:"O CO₂ (dióxido de carbono) libertado pela queima de combustíveis fósseis (petróleo, carvão, gás) é o principal responsável pelo efeito de estufa e pelo aquecimento global. As florestas absorvem CO₂ — por isso a desflorestação agrava o problema. Plantar árvores e usar energia limpa são passos fundamentais." },
    { q:"O que é a biodiversidade e por que é importante para as crianças?", a:[{t:"É a variedade de seres vivos no planeta, essencial para o equilíbrio da natureza",ok:true},{t:"É um tipo de energia renovável produzida por animais",ok:false},{t:"É o nome científico das florestas tropicais",ok:false}], exp:"Biodiversidade é a riqueza de espécies de plantas, animais e microrganismos que existem na Terra. Sem biodiversidade, perderíamos alimentos, medicamentos e o equilíbrio dos ecossistemas. A Convenção sobre a Diversidade Biológica reconhece que as crianças de hoje herdarão um planeta mais empobrecido se não agirmos." }
  ],
  digital: [
    { q:"Os direitos das crianças aplicam-se também ao mundo online?", a:[{t:"Sim, todos os direitos da Convenção se aplicam ao espaço digital",ok:true},{t:"Não, a internet é um espaço sem regras para crianças",ok:false},{t:"Só a partir dos 16 anos os direitos digitais são reconhecidos",ok:false}], exp:"Em 2021, o Comité dos Direitos da Criança das Nações Unidas publicou o Comentário Geral n.º 25, confirmando que todos os direitos da Convenção se aplicam ao ambiente digital. Isto inclui privacidade, proteção, expressão, educação e participação online." },
    { q:"O que é o ciberbullying e como se combate?", a:[{t:"É assédio ou intimidação online — combate-se com educação, denúncia e apoio",ok:true},{t:"É um jogo de computador perigoso",ok:false},{t:"Só acontece em redes sociais e não é muito grave",ok:false}], exp:"O ciberbullying é o assédio, humilhação ou ameaça através de meios digitais — mensagens, redes sociais, jogos online. Pode causar ansiedade, depressão e isolamento. Em Portugal, a Linha Internet Segura (1800 21 22 23) apoia vítimas e é possível denunciar às plataformas e às autoridades." },
    { q:"Que cuidados deve ter uma criança ao usar redes sociais?", a:[{t:"Não partilhar dados pessoais, ter perfil privado e contar a um adulto se algo correr mal",ok:true},{t:"Aceitar todos os pedidos de amizade para ter mais seguidores",ok:false},{t:"Partilhar a localização para que os amigos saibam onde está",ok:false}], exp:"A segurança online começa com boas práticas: perfil privado, não partilhar morada ou escola, não aceitar pedidos de estranhos, não responder a mensagens que causem desconforto e contar sempre a um adulto de confiança se algo parecer errado. A UNICEF tem guias gratuitos de literacia digital para crianças." },
    { q:"Qual é a idade mínima para criar conta nas principais redes sociais?", a:[{t:"13 anos na maioria das plataformas (Instagram, TikTok, YouTube)",ok:true},{t:"10 anos, com autorização dos pais",ok:false},{t:"18 anos em todas as plataformas",ok:false}], exp:"A maioria das grandes plataformas (Instagram, TikTok, YouTube, Snapchat) exige 13 anos de idade mínima, com base na lei norte-americana COPPA. Na UE, o RGPD fixa os 16 anos como regra geral, mas os países podem baixar para 13. Portugal fixou os 13 anos." },
    { q:"O que é a literacia digital?", a:[{t:"A capacidade de usar a tecnologia de forma segura, crítica e responsável",ok:true},{t:"Saber escrever código de programação",ok:false},{t:"Ter muitos seguidores nas redes sociais",ok:false}], exp:"A literacia digital é o conjunto de competências que permitem usar a internet e a tecnologia de forma segura, criativa e crítica: distinguir informação verdadeira de falsa, proteger os dados pessoais, comunicar com respeito e aproveitar as oportunidades digitais para aprender." },
    { q:"O que é o phishing e como se protege uma criança?", a:[{t:"É uma tentativa de enganar para obter dados pessoais — não clicar em links suspeitos",ok:true},{t:"É um jogo de pesca online muito popular",ok:false},{t:"É um vírus que apaga os ficheiros do computador",ok:false}], exp:"Phishing é quando alguém finge ser uma entidade de confiança (banco, escola, plataforma) para roubar palavras-passe ou dados pessoais. A proteção passa por não clicar em links suspeitos, não partilhar palavras-passe e contar sempre a um adulto se algo parecer errado." },
    { q:"O que são 'fake news' e como podemos identificá-las?", a:[{t:"São notícias falsas — verifica a fonte, a data e procura outras referências",ok:true},{t:"São notícias sobre acontecimentos futuros",ok:false},{t:"São notícias publicadas apenas nas redes sociais",ok:false}], exp:"Fake news são notícias falsas ou enganosas criadas para manipular opiniões. Para as identificar: verifica se a fonte é credível, procura a mesma notícia em vários meios, verifica a data e desconfia de títulos muito chocantes. O pensamento crítico é a melhor defesa contra a desinformação." },
    { q:"Qual linha de apoio podes contactar em Portugal se tiveres um problema online?", a:[{t:"Linha Internet Segura: 1800 21 22 23",ok:true},{t:"Linha de Apoio à Vítima: 116 006",ok:false},{t:"Linha de Saúde: 808 24 24 24",ok:false}], exp:"A Linha Internet Segura (1800 21 22 23) é gratuita, disponível em Portugal e apoia crianças e jovens com problemas online: ciberbullying, conteúdos perturbadores, assédio ou outros incidentes digitais. Podes também denunciar conteúdos ilegais em www.internetsegura.pt." }
  ]
};

