// ===== Conteúdo educativo e perguntas do quiz =====
// HISTORY, QUIZ_TIPS, QUIZ_ARTICLE, QUIZ_BY_THEME

export const HISTORY = [
  {
    title: "🎈 O Dia da Criança — 1 de Junho",
    text: "Celebra-se a 1 de junho em Portugal e em muitos outros países. A data foi escolhida em 1949 e celebrada pela primeira vez em 1950, para lembrar ao mundo os direitos das crianças. Em Portugal há festas e atividades nas escolas."
  },
  {
    title: "📜 A Declaração dos Direitos da Criança — 1959",
    text: "Em 1959, a ONU aprovou a Declaração dos Direitos da Criança, com 10 princípios. Reconhecia o direito à proteção, à educação, a um nome e a uma nacionalidade — um marco na história da humanidade!"
  },
  {
    title: "🌍 A Convenção dos Direitos da Criança — 1989",
    text: "A 20 de novembro de 1989, a ONU aprovou a Convenção sobre os Direitos da Criança — o tratado de direitos humanos mais ratificado da história. Os seus 54 artigos garantem sobrevivência, desenvolvimento, proteção e participação."
  },
  {
    title: "⚽ O Direito ao Brincar",
    text: "O artigo 31.º garante o direito ao descanso, ao lazer e ao brincar. Brincar não é só diversão — é essencial para o desenvolvimento do cérebro, da criatividade e das competências sociais!"
  },
  {
    title: "📚 O Direito à Educação",
    text: "O artigo 28.º garante o direito à educação. Em Portugal, o ensino é obrigatório e gratuito até aos 18 anos. No mundo, mais de 270 milhões de crianças ainda estão fora da escola, e a UNICEF trabalha para mudar isso."
  },
  {
    title: "💊 O Direito à Saúde",
    text: "O artigo 24.º garante o direito ao mais alto nível de saúde possível. Em Portugal há acesso ao Serviço Nacional de Saúde e ao Plano Nacional de Vacinação. No mundo, a UNICEF distribui vacinas e água potável."
  },
  {
    title: "🛡️ O Direito à Proteção",
    text: "Os artigos 19.º e 37.º protegem as crianças contra violência, abuso e exploração. Em Portugal, a CPCJ acompanha crianças em risco. Se uma criança estiver em perigo, liga 116 111 — a linha SOS Criança."
  },
  {
    title: "🗣️ O Direito a Ser Ouvido",
    text: "O artigo 12.º garante o direito de opinar em todas as decisões que te afetam — em casa, na escola e perante os governos! Em Portugal existem parlamentos jovens onde podes participar."
  },
  {
    title: "🌱 O Futuro das Crianças — Os ODS",
    text: "Em 2015, a ONU aprovou os 17 Objetivos de Desenvolvimento Sustentável, a cumprir até 2030: acabar com a pobreza, garantir saúde e educação de qualidade para todos. As crianças de hoje são as agentes desta mudança!"
  },
  {
    title: "🌟 A UNICEF — A Guardiã dos Direitos",
    text: "A UNICEF nasceu em 1946, após a Segunda Guerra Mundial, para ajudar as crianças afetadas pelo conflito. Hoje atua em mais de 190 países. Em Portugal, o Comité Português angaria fundos para os seus programas!"
  },
  {
    title: "🪪 O Direito à Identidade",
    text: "O artigo 7.º garante o direito a ser registado logo após o nascimento, com um nome e uma nacionalidade. Ainda assim, 150 milhões de crianças com menos de 5 anos não têm registo de nascimento. O teu nome é o primeiro direito que recebes!"
  },
  {
    title: "👨‍👩‍👧 O Direito à Família",
    text: "O artigo 9.º garante que a criança não deve ser separada dos pais, exceto para a sua própria proteção. A família é o primeiro lugar onde aprendemos amor, segurança e valores."
  },
  {
    title: "✈️ O Direito das Crianças Refugiadas",
    text: "Quase 49 milhões de crianças vivem deslocadas no mundo, fugindo de guerras e violência. O artigo 22.º garante que as crianças refugiadas têm exatamente os mesmos direitos que todas as outras. Ser refugiado não apaga os teus direitos!"
  },
  {
    title: "🚫 O Direito a Não Trabalhar em Condições Perigosas",
    text: "O artigo 32.º proíbe o trabalho infantil que prejudique a saúde, a segurança ou a educação da criança. Ainda há 138 milhões de crianças em trabalho infantil no mundo, mas o número tem vindo a descer. As crianças têm direito a ser crianças!"
  },
  {
    title: "🗣️ O Direito à Liberdade de Expressão",
    text: "O artigo 13.º garante o direito de procurar, receber e partilhar informação e ideias — por palavras, arte ou escrita. A tua voz importa!"
  },
  {
    title: "🔒 O Direito à Privacidade",
    text: "O artigo 16.º protege a vida privada, a família e a correspondência das crianças. Em Portugal, o RGPD dá proteção especial aos dados de menores de 13 anos. Cuida da tua privacidade online!"
  },
  {
    title: "🌍 O Direito à Cultura e à Língua",
    text: "O artigo 30.º garante às crianças de minorias o direito à sua cultura e à sua língua. No mundo há cerca de 7 000 línguas vivas — cada uma é um tesouro único da humanidade!"
  },
  {
    title: "♿ O Direito à Inclusão",
    text: "O artigo 23.º garante que as crianças com deficiência têm direito a uma vida plena e digna, com acesso à educação e à participação social. Aprender todos juntos é um direito de todos!"
  },
  {
    title: "🌱 O Direito a um Ambiente Saudável",
    text: "As crianças têm direito a crescer num ambiente limpo e saudável. As alterações climáticas ameaçam este direito: mais de mil milhões vivem em zonas de risco climático extremo. Separa o lixo, poupa água — o planeta precisa de ti!"
  },
  {
    title: "💻 Os Direitos Digitais das Crianças",
    text: "Em 2021, a ONU confirmou que todos os direitos da Convenção se aplicam também ao mundo online — incluindo privacidade e proteção contra o ciberbullying. Em Portugal, a Linha Internet Segura (1800 21 22 23) apoia quem precisar."
  }
];

export const QUIZ_TIPS = {
  historia:     "O Dia da Criança celebra-se a 1 de junho. A Convenção dos Direitos da Criança foi aprovada em 1989.",
  declaracao:   "A Declaração dos Direitos da Criança foi aprovada pelas Nações Unidas em 1959, com 10 princípios.",
  convencao:    "A Convenção sobre os Direitos da Criança de 1989 tem 54 artigos e foi ratificada por quase todos os países.",
  brincar:      "O artigo 31.º da Convenção garante o direito ao brincar, ao descanso e ao lazer.",
  educacao:     "O artigo 28.º garante o direito à educação. Em Portugal é obrigatória até aos 18 anos.",
  saude:        "O artigo 24.º garante o direito à saúde. A UNICEF distribui vacinas e cuidados básicos no mundo.",
  protecao:     "Os artigos 19.º e 37.º protegem as crianças contra violência e exploração. SOS Criança: 116 111.",
  participacao: "O artigo 12.º garante às crianças o direito de serem ouvidas nas decisões que as afetam.",
  futuro:       "Os 17 ODS das Nações Unidas, aprovados em 2015, incluem metas para acabar com a pobreza e garantir educação.",
  unicef:       "A UNICEF foi criada em 1946 e trabalha em mais de 190 países para defender os direitos das crianças.",
  identidade:   "O artigo 7.º garante o direito a um nome e a uma nacionalidade desde o nascimento.",
  familia:      "O artigo 9.º garante que a criança não seja separada dos pais, exceto em situações de proteção.",
  refugiados:   "O artigo 22.º protege as crianças refugiadas com os mesmos direitos das outras crianças.",
  trabalho:     "O artigo 32.º proíbe o trabalho infantil perigoso e prejudicial ao desenvolvimento da criança.",
  expressao:    "O artigo 13.º garante a liberdade de expressão — as crianças podem procurar e partilhar informação.",
  privacidade:  "O artigo 16.º protege a privacidade das crianças — a sua vida pessoal e correspondência.",
  cultura:      "O artigo 30.º garante às crianças de minorias o direito à sua língua, cultura e religião.",
  deficiencia:  "O artigo 23.º garante que as crianças com deficiência têm direito a apoio especial e plena inclusão.",
  ambiente:     "As crianças têm direito a crescer num ambiente saudável — base dos ODS 13, 14 e 15.",
  digital:      "Os direitos digitais das crianças aplicam os artigos da Convenção ao mundo online e às redes sociais."
};

export const QUIZ_ARTICLE = {
  historia:     null,
  declaracao:   null,
  convencao:    null,
  brincar:      "Art. 31.º",
  educacao:     "Art. 28.º",
  saude:        "Art. 24.º",
  protecao:     "Art. 19.º / 37.º",
  participacao: "Art. 12.º",
  futuro:       "ODS 2030",
  unicef:       null,
  identidade:   "Art. 7.º",
  familia:      "Art. 9.º / 10.º",
  refugiados:   "Art. 22.º",
  trabalho:     "Art. 32.º",
  expressao:    "Art. 13.º",
  privacidade:  "Art. 16.º",
  cultura:      "Art. 30.º",
  deficiencia:  "Art. 23.º",
  ambiente:     "ODS 13-15",
  digital:      "Art. 16.º / 17.º"
};

export const QUIZ_BY_THEME = {
  historia: [
    { q:"Em que data se celebra o Dia da Criança em Portugal?", a:[{t:"1 de junho",ok:true},{t:"1 de maio",ok:false},{t:"20 de novembro",ok:false}], exp:"O Dia Internacional da Criança é a 1 de junho, decidido em 1949 e celebrado pela primeira vez em 1950. Já o 20 de novembro é o Dia Universal da Criança, data da Convenção de 1989." },
    { q:"Quem escolheu o 1 de junho como Dia da Criança, em 1949?", a:[{t:"A Federação Democrática Internacional das Mulheres",ok:true},{t:"As Nações Unidas",ok:false},{t:"A UNICEF",ok:false}], exp:"Em novembro de 1949, em Moscovo, a Federação Democrática Internacional das Mulheres escolheu o 1 de junho como Dia Internacional de Proteção das Crianças, celebrado pela primeira vez em 1950." },
    { q:"Qual é o objetivo do Dia da Criança?", a:[{t:"Celebrar e defender os direitos e o bem-estar das crianças",ok:true},{t:"Assinalar o fim do ano letivo",ok:false},{t:"Comemorar o início do verão",ok:false}], exp:"O Dia da Criança serve para lembrar que todas as crianças têm direitos — à educação, à saúde, ao brincar e à proteção — e que garanti-los é responsabilidade de todos." },
    { q:"Em que ano surgiu o primeiro Dia da Criança?", a:[{t:"1950",ok:true},{t:"1989",ok:false},{t:"1945",ok:false}], exp:"O Dia Internacional da Criança surgiu em 1950, cinco anos após o fim da Segunda Guerra Mundial, num período em que o mundo procurava reconstruir-se e proteger as gerações mais novas." },
    { q:"Em Portugal, o Dia da Criança é celebrado com que tipo de atividades?", a:[{t:"Festas, prendas e atividades especiais nas escolas",ok:true},{t:"Apenas com um feriado nacional",ok:false},{t:"Com uma cerimónia oficial no Parlamento",ok:false}], exp:"Em Portugal, o 1 de junho é celebrado com festas nas escolas, prendas, atividades ao ar livre e ações de sensibilização para os direitos das crianças." }
  ],
  declaracao: [
    { q:"Em que ano foi aprovada a Declaração dos Direitos da Criança?", a:[{t:"1959",ok:true},{t:"1989",ok:false},{t:"1950",ok:false}], exp:"A Declaração foi aprovada pela ONU a 20 de novembro de 1959. Trinta anos depois, em 1989, surgiu a Convenção — já com força legal obrigatória." },
    { q:"Quantos princípios tinha a Declaração dos Direitos da Criança de 1959?", a:[{t:"10 princípios",ok:true},{t:"54 artigos",ok:false},{t:"7 capítulos",ok:false}], exp:"A Declaração de 1959 tinha 10 princípios, mas não era juridicamente vinculativa — era uma declaração de intenções. Foi o primeiro documento internacional dedicado só aos direitos das crianças." },
    { q:"O que reconhecia a Declaração dos Direitos da Criança de 1959?", a:[{t:"Que todas as crianças têm direito à proteção, educação, nome e nacionalidade",ok:true},{t:"Que as crianças devem trabalhar para ajudar as famílias",ok:false},{t:"Que só as crianças de países ricos têm direito à educação",ok:false}], exp:"A Declaração afirmava que todas as crianças, sem discriminação, têm direito a proteção especial, a um nome, a uma nacionalidade, a cuidados de saúde e a educação gratuita." },
    { q:"Qual foi a importância histórica da Declaração de 1959?", a:[{t:"Foi o primeiro documento da ONU dedicado exclusivamente aos direitos das crianças",ok:true},{t:"Foi a primeira lei obrigatória sobre crianças do mundo",ok:false},{t:"Criou a UNICEF",ok:false}], exp:"Já existia a Declaração de Genebra de 1924 (Liga das Nações), mas a de 1959 foi o primeiro documento da ONU dedicado só aos direitos da criança. Abriu caminho para a Convenção de 1989." },
    { q:"A Declaração de 1959 era juridicamente obrigatória para os países?", a:[{t:"Não — era uma declaração de intenções, sem força legal",ok:true},{t:"Sim, todos os países eram obrigados a cumpri-la",ok:false},{t:"Sim, mas só para os países fundadores da ONU",ok:false}], exp:"A Declaração era apenas um compromisso moral, sem força legal. Já a Convenção de 1989, com 54 artigos, é um tratado internacional com força de lei para os países que a ratificaram." },
    { q:"Que evento histórico motivou maior atenção aos direitos das crianças após 1945?", a:[{t:"A Segunda Guerra Mundial, que deixou milhões de crianças sem lar",ok:true},{t:"A Revolução Industrial, que usou trabalho infantil nas fábricas",ok:false},{t:"A Primeira Guerra Mundial, que criou a Liga das Nações",ok:false}], exp:"O fim da Segunda Guerra Mundial deixou milhões de crianças órfãs, deslocadas e traumatizadas — o que impulsionou a criação da UNICEF em 1946 e, mais tarde, a Declaração de 1959." }
  ],
  convencao: [
    { q:"Em que data foi aprovada a Convenção sobre os Direitos da Criança?", a:[{t:"20 de novembro de 1989",ok:true},{t:"1 de junho de 1989",ok:false},{t:"20 de novembro de 1959",ok:false}], exp:"A Convenção foi aprovada pela Assembleia Geral da ONU a 20 de novembro de 1989. Por isso, esta data é celebrada como o Dia Universal da Criança em todo o mundo." },
    { q:"Em que ano Portugal ratificou a Convenção dos Direitos da Criança?", a:[{t:"1990",ok:true},{t:"1989",ok:false},{t:"1995",ok:false}], exp:"Portugal ratificou a Convenção a 21 de setembro de 1990, poucos meses após a sua aprovação pelas Nações Unidas — um dos primeiros países a fazê-lo." },
    { q:"Quantos artigos tem a Convenção dos Direitos da Criança?", a:[{t:"54 artigos",ok:true},{t:"10 artigos",ok:false},{t:"100 artigos",ok:false}], exp:"A Convenção tem 54 artigos organizados em torno de 4 pilares: sobrevivência, desenvolvimento, proteção e participação. É o tratado de direitos humanos mais ratificado da história." },
    { q:"Quais são os 4 pilares principais da Convenção dos Direitos da Criança?", a:[{t:"Sobrevivência, desenvolvimento, proteção e participação",ok:true},{t:"Educação, saúde, habitação e alimentação",ok:false},{t:"Paz, liberdade, igualdade e fraternidade",ok:false}], exp:"Os 4 pilares da Convenção são o direito à sobrevivência, ao desenvolvimento pleno, à proteção contra abusos e à participação na vida familiar e social." },
    { q:"A Convenção dos Direitos da Criança é o tratado de direitos humanos com mais países a assiná-lo?", a:[{t:"Sim, quase todos os países do mundo a ratificaram",ok:true},{t:"Não, a Declaração Universal dos Direitos Humanos tem mais assinaturas",ok:false},{t:"Não, apenas metade dos países a assinou",ok:false}], exp:"Com 196 países signatários, a Convenção dos Direitos da Criança é o tratado de direitos humanos mais ratificado da história das Nações Unidas." }
  ],
  brincar: [
    { q:"Qual é o artigo da Convenção que garante o direito ao brincar?", a:[{t:"Artigo 31.º",ok:true},{t:"Artigo 24.º",ok:false},{t:"Artigo 12.º",ok:false}], exp:"O artigo 31.º garante o direito de todas as crianças ao descanso, ao lazer, ao brincar e a atividades recreativas adequadas à sua idade." },
    { q:"Por que é que brincar é considerado um direito e não apenas diversão?", a:[{t:"Porque é essencial para o desenvolvimento do cérebro e das competências sociais",ok:true},{t:"Porque as crianças ficam mais calmas",ok:false},{t:"Porque é obrigatório por lei brincar todos os dias",ok:false}], exp:"Brincar é fundamental para o desenvolvimento cognitivo, emocional e social — é através do jogo que aprendemos a comunicar, a colaborar e a lidar com as emoções." },
    { q:"O que mostram os estudos sobre crianças que brincam livremente?", a:[{t:"São mais criativas, resilientes e têm melhor saúde mental",ok:true},{t:"Têm piores resultados académicos",ok:false},{t:"São mais difíceis de controlar na escola",ok:false}], exp:"A investigação mostra que o brincar livre — sem instruções de adultos — desenvolve a criatividade, a autonomia e a capacidade de gerir emoções e conflitos." },
    { q:"O que mais inclui o direito ao brincar, além do jogo?", a:[{t:"Descanso, lazer e atividades recreativas e culturais",ok:true},{t:"Apenas jogar videojogos",ok:false},{t:"Só atividades desportivas organizadas",ok:false}], exp:"O artigo 31.º é abrangente: inclui o direito ao repouso, às férias escolares, à participação em atividades artísticas e culturais e ao acesso a espaços de recreio seguros." },
    { q:"Qual das seguintes situações viola o direito ao brincar das crianças?", a:[{t:"Substituir todos os intervalos escolares por estudo",ok:true},{t:"Ter um parque infantil na escola",ok:false},{t:"Ter aulas de música e teatro",ok:false}], exp:"O artigo 31.º protege os intervalos escolares, as férias e o tempo livre. A OMS recomenda pelo menos 60 minutos de atividade física diária para crianças em idade escolar." },
    { q:"Em que artigo da Convenção se baseia o direito das crianças a participar em atividades culturais?", a:[{t:"Artigo 31.º — direito ao lazer, jogo e participação cultural",ok:true},{t:"Artigo 17.º — acesso a informação nos media",ok:false},{t:"Artigo 29.º — objetivos da educação",ok:false}], exp:"O artigo 31.º reconhece o direito a participar plenamente na vida cultural e artística. Os Estados devem garantir espaços e recursos para todas as crianças, seja qual for a sua origem." }
  ],
  educacao: [
    { q:"Qual é o artigo da Convenção que garante o direito à educação?", a:[{t:"Artigo 28.º",ok:true},{t:"Artigo 31.º",ok:false},{t:"Artigo 19.º",ok:false}], exp:"O artigo 28.º garante o direito à educação. O ensino primário deve ser obrigatório e gratuito, e os países devem promover também o acesso ao secundário e ao superior." },
    { q:"Até que idade é o ensino obrigatório em Portugal?", a:[{t:"Até aos 18 anos",ok:true},{t:"Até aos 15 anos",ok:false},{t:"Até aos 12 anos",ok:false}], exp:"Em Portugal, desde 2009, a escolaridade obrigatória foi alargada para 12 anos, o que significa estudar até completar o ensino secundário ou fazer 18 anos." },
    { q:"Quantas crianças ainda estão fora da escola em todo o mundo?", a:[{t:"Mais de 270 milhões de crianças",ok:true},{t:"10 milhões de crianças",ok:false},{t:"50 milhões de crianças",ok:false}], exp:"Segundo a UNESCO, mais de 270 milhões de crianças e jovens estão fora da escola em todo o mundo — sobretudo por pobreza, conflitos armados e distância das escolas." },
    { q:"O que faz a UNICEF em relação ao direito à educação?", a:[{t:"Trabalha para garantir que todas as crianças do mundo possam estudar",ok:true},{t:"Constrói escolas apenas na Europa",ok:false},{t:"Distribui apenas livros escolares",ok:false}], exp:"A UNICEF trabalha em todo o mundo para garantir acesso à educação, sobretudo em zonas de conflito. Financia escolas, forma professores e apoia programas de inclusão." },
    { q:"O que garante o artigo 29.º da Convenção em relação à educação?", a:[{t:"Que a educação deve desenvolver a personalidade, talentos e respeito pelos outros",ok:true},{t:"Que a educação deve focar-se apenas em matemática e línguas",ok:false},{t:"Que o Estado pode escolher o que as crianças aprendem sem ouvir os pais",ok:false}], exp:"O artigo 29.º define os objetivos da educação: desenvolver a personalidade, os talentos e as capacidades da criança, preparando-a para uma vida responsável e livre, com respeito pelos direitos humanos." },
    { q:"O que é o ensino inclusivo e como se relaciona com os direitos das crianças?", a:[{t:"É um sistema em que todas as crianças aprendem juntas, independentemente das suas capacidades",ok:true},{t:"É ensino à distância através da internet",ok:false},{t:"É um sistema de escolas privadas acessíveis a todos",ok:false}], exp:"A educação inclusiva assegura que nenhuma criança fica excluída da escola por deficiência, origem étnica, género ou pobreza. Portugal tem avançado neste modelo desde 2018." }
  ],
  saude: [
    { q:"Qual é o artigo da Convenção que garante o direito à saúde?", a:[{t:"Artigo 24.º",ok:true},{t:"Artigo 31.º",ok:false},{t:"Artigo 28.º",ok:false}], exp:"O artigo 24.º garante o direito ao mais alto nível possível de saúde e a serviços médicos. Os países devem combater a mortalidade infantil e garantir cuidados básicos." },
    { q:"A que serviços de saúde têm acesso as crianças em Portugal?", a:[{t:"Serviço Nacional de Saúde, vacinas e médico de família",ok:true},{t:"Apenas a urgências hospitalares",ok:false},{t:"Só as que têm seguro de saúde privado",ok:false}], exp:"Em Portugal, todas as crianças têm acesso gratuito ao SNS, ao Plano Nacional de Vacinação — que previne doenças como o sarampo — e a um médico de família." },
    { q:"O que distribui a UNICEF para ajudar a saúde das crianças no mundo?", a:[{t:"Vacinas, alimentos terapêuticos e água potável",ok:true},{t:"Apenas medicamentos caros",ok:false},{t:"Só equipamento hospitalar sofisticado",ok:false}], exp:"A UNICEF fornece vacinas a metade das crianças do mundo, distribui alimentos terapêuticos a crianças com desnutrição severa e apoia o abastecimento de água potável." },
    { q:"O que é o Plano Nacional de Vacinação (PNV) em Portugal?", a:[{t:"Um programa gratuito de vacinação para todas as crianças portuguesas",ok:true},{t:"Um plano pago apenas para famílias ricas",ok:false},{t:"Um programa só para adultos",ok:false}], exp:"O PNV é gratuito e universal — cobre todas as crianças portuguesas e previne doenças graves como a tosse convulsa, o sarampo, a hepatite B e a meningite." },
    { q:"Por que morrem ainda muitas crianças de doenças preveníveis no mundo?", a:[{t:"Porque não têm acesso a vacinas, água potável e cuidados básicos",ok:true},{t:"Porque as vacinas não funcionam nesses países",ok:false},{t:"Porque os países não querem aderir à OMS",ok:false}], exp:"A falta de acesso a vacinas, água potável e cuidados médicos básicos é a principal causa de morte infantil evitável — por isso a UNICEF fornece vacinas a metade das crianças do mundo." },
    { q:"O que significa 'o mais alto nível de saúde possível' no artigo 24.º da Convenção?", a:[{t:"Que cada país deve garantir o melhor cuidado de saúde ao seu alcance para todas as crianças",ok:true},{t:"Que todas as crianças têm direito a hospitais privados",ok:false},{t:"Que a saúde é mais importante do que a educação",ok:false}], exp:"O artigo 24.º reconhece que os recursos de cada país são diferentes — mas todos devem melhorar progressivamente o acesso das crianças à saúde, à nutrição e à água potável." }
  ],
  protecao: [
    { q:"Quais são os artigos da Convenção que protegem as crianças contra violência e abuso?", a:[{t:"Artigos 19.º e 37.º",ok:true},{t:"Artigos 24.º e 28.º",ok:false},{t:"Artigos 12.º e 31.º",ok:false}], exp:"O artigo 19.º protege as crianças contra todas as formas de violência física e psicológica. O artigo 37.º proíbe a tortura, os tratamentos degradantes e a privação ilegal de liberdade." },
    { q:"Qual é o número da linha de apoio SOS Criança em Portugal?", a:[{t:"116 111",ok:true},{t:"112",ok:false},{t:"800 202 202",ok:false}], exp:"O 116 111 é a linha dedicada a crianças e jovens em perigo em Portugal. Funciona 24 horas por dia, é gratuita e confidencial — qualquer pessoa pode ligar." },
    { q:"O que é a CPCJ?", a:[{t:"Comissão de Proteção de Crianças e Jovens",ok:true},{t:"Centro de Promoção Cultural Juvenil",ok:false},{t:"Comité Português da UNICEF",ok:false}], exp:"A CPCJ é uma instituição oficial portuguesa que intervém para proteger crianças e jovens em risco. Existem comissões em todo o país, a trabalhar com famílias, escolas e serviços sociais." },
    { q:"O que proibem os artigos de proteção da Convenção dos Direitos da Criança?", a:[{t:"Toda a forma de violência, trabalho perigoso e privação de liberdade",ok:true},{t:"Apenas a violência física",ok:false},{t:"Só o trabalho infantil em fábricas",ok:false}], exp:"A Convenção proíbe todas as formas de maus-tratos — físicos, psicológicos, sexuais —, o trabalho infantil perigoso, o tráfico de crianças e qualquer privação ilegal da liberdade." },
    { q:"O que deve fazer uma criança ou adulto que suspeite de maus-tratos a uma criança?", a:[{t:"Contactar a linha 116 111 ou falar com a CPCJ da sua área",ok:true},{t:"Aguardar que a situação se resolva sozinha",ok:false},{t:"Só agir se tiver provas absolutas",ok:false}], exp:"Quem suspeitar de maus-tratos pode e deve ligar ao 116 111 ou contactar a CPCJ local. Não são precisas provas absolutas — denunciar é proteger." },
    { q:"O que é o tráfico de crianças e como é combatido?", a:[{t:"É a exploração de crianças através de recrutamento e transporte forçados — combatido com leis e cooperação internacional",ok:true},{t:"É apenas o tráfico de drogas envolvendo menores",ok:false},{t:"Só acontece em países em guerra",ok:false}], exp:"O tráfico de crianças inclui recrutar, transportar ou acolher menores para exploração sexual, trabalho forçado ou mendicidade. É proibido pelo artigo 35.º e combatido pela INTERPOL, EUROPOL e UNICEF." }
  ],
  participacao: [
    { q:"Qual é o artigo da Convenção que garante às crianças o direito a ser ouvidas?", a:[{t:"Artigo 12.º",ok:true},{t:"Artigo 24.º",ok:false},{t:"Artigo 37.º",ok:false}], exp:"O artigo 12.º afirma que as crianças têm o direito de expressar livremente a sua opinião nas questões que as afetam, tendo em conta a sua idade e maturidade." },
    { q:"Em que espaços podem as crianças em Portugal exercer o direito à participação?", a:[{t:"Nos parlamentos jovens e conselhos municipais de jovens",ok:true},{t:"Apenas no conselho de turma",ok:false},{t:"Só depois dos 18 anos",ok:false}], exp:"Em Portugal existem parlamentos jovens e conselhos municipais de jovens, onde crianças e adolescentes podem debater e apresentar propostas." },
    { q:"O direito à participação aplica-se em que contextos?", a:[{t:"Nas escolas, nas famílias e nos governos",ok:true},{t:"Apenas em assembleias internacionais",ok:false},{t:"Só em atividades extracurriculares",ok:false}], exp:"Aplica-se em todos os contextos onde se tomam decisões que afetam as crianças: em casa, na escola, nos tribunais, nos serviços sociais e a nível local e nacional." },
    { q:"Por que é importante ouvir a opinião das crianças?", a:[{t:"Porque as decisões que as afetam ficam mais justas e adequadas",ok:true},{t:"Porque as crianças sabem sempre melhor que os adultos",ok:false},{t:"Porque é obrigatório por lei que sejam elas a decidir tudo",ok:false}], exp:"Ouvir as crianças não significa que decidem tudo — significa que a sua perspetiva é considerada, tornando as decisões mais justas e adaptadas às suas necessidades." },
    { q:"Como se chama o mecanismo da ONU que avalia se os países respeitam a Convenção?", a:[{t:"Comité dos Direitos da Criança das Nações Unidas",ok:true},{t:"Tribunal Internacional de Justiça",ok:false},{t:"Conselho de Segurança da ONU",ok:false}], exp:"O Comité dos Direitos da Criança é um órgão independente de 18 especialistas que analisa os relatórios dos países e faz recomendações. Portugal é regularmente avaliado por este Comité." }
  ],
  futuro: [
    { q:"Quantos Objetivos de Desenvolvimento Sustentável (ODS) existem?", a:[{t:"17 objetivos",ok:true},{t:"10 objetivos",ok:false},{t:"27 objetivos",ok:false}], exp:"Em setembro de 2015, os países membros da ONU aprovaram a Agenda 2030 com 17 ODS, para erradicar a pobreza, proteger o planeta e garantir prosperidade até 2030." },
    { q:"Em que ano foram aprovados os Objetivos de Desenvolvimento Sustentável?", a:[{t:"2015",ok:true},{t:"2000",ok:false},{t:"2020",ok:false}], exp:"Os 17 ODS foram aprovados na Cimeira das Nações Unidas de setembro de 2015, para atingir até 2030, com governos, empresas e cidadãos de todo o mundo envolvidos." },
    { q:"Qual ODS se refere diretamente à educação de qualidade?", a:[{t:"ODS 4 — Educação de Qualidade",ok:true},{t:"ODS 1 — Erradicar a Pobreza",ok:false},{t:"ODS 3 — Saúde de Qualidade",ok:false}], exp:"O ODS 4 estabelece o objetivo de garantir educação inclusiva, equitativa e de qualidade para todos até 2030, incluindo o pré-escolar e a aprendizagem ao longo da vida." },
    { q:"Por que são as crianças de hoje importantes para o futuro sustentável?", a:[{t:"Porque serão os agentes de mudança que implementarão soluções para os problemas globais",ok:true},{t:"Porque os adultos já não conseguem resolver os problemas do planeta",ok:false},{t:"Porque só as crianças votam nos ODS",ok:false}], exp:"As crianças de hoje crescerão num mundo em transformação e serão as líderes, cientistas e cidadãs que implementarão soluções para as alterações climáticas e a desigualdade." },
    { q:"Qual ODS está diretamente ligado ao fim da pobreza extrema?", a:[{t:"ODS 1 — Erradicar a Pobreza",ok:true},{t:"ODS 8 — Trabalho Digno",ok:false},{t:"ODS 10 — Reduzir as Desigualdades",ok:false}], exp:"O ODS 1 visa erradicar a pobreza extrema até 2030. Cerca de 356 milhões de crianças vivem com menos de 2,15 dólares por dia — acabar com a pobreza infantil é essencial para um futuro sustentável." },
    { q:"O que podem as crianças fazer hoje para contribuir para os ODS?", a:[{t:"Agir no dia a dia: poupar energia, reciclar, respeitar os outros e sensibilizar a comunidade",ok:true},{t:"Nada — os ODS são apenas para governos",ok:false},{t:"Esperar ter 18 anos para começar a participar",ok:false}], exp:"Os ODS são para todos. As crianças contribuem através das escolhas diárias, da participação na escola e comunidade e do envolvimento em projetos locais — cada ação conta." }
  ],
  unicef: [
    { q:"Em que ano foi criada a UNICEF?", a:[{t:"1946",ok:true},{t:"1959",ok:false},{t:"1989",ok:false}], exp:"A UNICEF foi criada a 11 de dezembro de 1946, pela Assembleia Geral das Nações Unidas, para ajudar as crianças afetadas pela Segunda Guerra Mundial." },
    { q:"Em quantos países trabalha a UNICEF?", a:[{t:"Mais de 190 países e territórios",ok:true},{t:"Apenas 50 países",ok:false},{t:"Só nos países mais ricos",ok:false}], exp:"A UNICEF está presente em mais de 190 países e territórios, praticamente em todo o mundo — sobretudo em zonas de conflito e países com muita pobreza." },
    { q:"O que significa a sigla UNICEF?", a:[{t:"Fundo das Nações Unidas para a Infância",ok:true},{t:"União Internacional de Crianças e Famílias",ok:false},{t:"Unidade Nacional de Cuidados de Emergência para a Família",ok:false}], exp:"UNICEF vem do inglês 'United Nations Children's Fund' — o nome foi encurtado em 1953, mas o acrónimo manteve-se. Em português é o Fundo das Nações Unidas para a Infância." },
    { q:"O que faz o Comité Português da UNICEF?", a:[{t:"Sensibiliza para os direitos das crianças e angaria fundos para programas no mundo",ok:true},{t:"Gere hospitais pediátricos em Portugal",ok:false},{t:"Substitui o Estado na proteção das crianças portuguesas",ok:false}], exp:"O Comité Português da UNICEF é uma organização não governamental que sensibiliza a sociedade portuguesa e angaria donativos para os programas da UNICEF no mundo." },
    { q:"Qual é um dos principais programas de nutrição da UNICEF para crianças em risco?", a:[{t:"Distribuição de alimentos terapêuticos prontos a usar (RUTF) para desnutrição severa",ok:true},{t:"Vales de desconto em supermercados de países ricos",ok:false},{t:"Distribuição de vitaminas apenas em hospitais privados",ok:false}], exp:"O RUTF (alimento terapêutico pronto a usar) é uma pasta nutritiva que a UNICEF distribui em zonas de crise para tratar a desnutrição severa. É barato, não precisa de refrigeração e salva milhões de vidas." },
    { q:"O 20 de novembro é o Dia Universal da Criança — porquê esta data?", a:[{t:"Porque foi nesse dia de 1989 que a Convenção dos Direitos da Criança foi aprovada",ok:true},{t:"Porque foi o aniversário da fundação da UNICEF",ok:false},{t:"Porque é o dia em que a ONU foi criada",ok:false}], exp:"A 20 de novembro de 1989, a ONU adotou a Convenção sobre os Direitos da Criança — por isso esta data é hoje o Dia Universal da Criança em todo o mundo." }
  ],
  identidade: [
    { q:"Qual é o artigo da Convenção que garante o direito a um nome e a uma nacionalidade?", a:[{t:"Artigo 7.º",ok:true},{t:"Artigo 12.º",ok:false},{t:"Artigo 24.º",ok:false}], exp:"O artigo 7.º estipula que toda a criança tem direito a ser registada logo após o nascimento, a ter um nome e a adquirir uma nacionalidade — o primeiro passo para garantir todos os outros direitos." },
    { q:"O que é o registo de nascimento e por que é importante?", a:[{t:"É o documento que prova a existência legal da criança e garante os seus direitos",ok:true},{t:"É apenas uma formalidade sem consequências práticas",ok:false},{t:"Só é obrigatório nos países ricos",ok:false}], exp:"Sem registo de nascimento, uma criança não existe legalmente: não pode ir à escola, aceder a cuidados de saúde ou ter passaporte. Ainda há 150 milhões de crianças com menos de 5 anos por registar." },
    { q:"Qual artigo protege a identidade da criança (nome, nacionalidade e relações familiares)?", a:[{t:"Artigo 8.º",ok:true},{t:"Artigo 3.º",ok:false},{t:"Artigo 19.º",ok:false}], exp:"O artigo 8.º obriga os Estados a respeitar e preservar a identidade da criança — nome, nacionalidade e vínculos familiares — e a ajudá-la a recuperá-los se forem ilegalmente retirados." },
    { q:"Quantas crianças no mundo nascem sem registo?", a:[{t:"Cerca de 150 milhões",ok:true},{t:"Menos de 1 milhão",ok:false},{t:"Cerca de 50 milhões",ok:false}], exp:"Segundo a UNICEF, cerca de 150 milhões de crianças menores de 5 anos não têm registo de nascimento, sobretudo na África Subsariana e na Ásia do Sul." },
    { q:"O que é uma criança apátrida?", a:[{t:"Uma criança sem nacionalidade reconhecida por nenhum Estado",ok:true},{t:"Uma criança que perdeu os pais",ok:false},{t:"Uma criança que vive em mais do que um país",ok:false}], exp:"A apatridia ocorre quando uma criança não é reconhecida como nacional por nenhum país. Sem nacionalidade, fica excluída de direitos básicos — protegida pela Convenção de 1954 sobre os Apátridas e pelo artigo 7.º da CDC." },
    { q:"Porque é que algumas crianças não recebem registo de nascimento logo após nascer?", a:[{t:"Por pobreza, distância dos serviços, conflitos armados ou discriminação",ok:true},{t:"Porque os pais preferem esperar até a criança falar",ok:false},{t:"Porque a ONU proibiu o registo em certos países",ok:false}], exp:"As principais barreiras são a distância aos serviços de registo civil, os custos, a discriminação de grupos minoritários e os conflitos que destroem infraestruturas. A UNICEF apoia o registo em zonas de crise." }
  ],
  familia: [
    { q:"Qual é o artigo da Convenção que garante que a criança não seja separada dos pais?", a:[{t:"Artigo 9.º",ok:true},{t:"Artigo 7.º",ok:false},{t:"Artigo 31.º",ok:false}], exp:"O artigo 9.º estabelece que a criança não deve ser separada dos pais contra a sua vontade, exceto quando isso for necessário para o seu bem-estar — por exemplo, em casos de abuso ou negligência graves." },
    { q:"O que garante o artigo 10.º da Convenção?", a:[{t:"O direito à reunificação familiar quando pais e filhos vivem em países diferentes",ok:true},{t:"O direito a ter sempre dois pais",ok:false},{t:"O direito a escolher com qual dos pais viver",ok:false}], exp:"O artigo 10.º garante que os pedidos de reunificação familiar — quando pais e filhos vivem em países diferentes — sejam tratados de forma positiva, rápida e humana pelos governos." },
    { q:"O que diz o artigo 18.º sobre o papel dos pais?", a:[{t:"Os pais têm responsabilidade conjunta pela criação e desenvolvimento da criança",ok:true},{t:"Só o pai é responsável pela criança",ok:false},{t:"O Estado é o principal responsável pela criação das crianças",ok:false}], exp:"O artigo 18.º reconhece que ambos os pais têm responsabilidades comuns na criação da criança. O Estado deve apoiá-los, por exemplo através de serviços de apoio à família e creches." },
    { q:"O que acontece quando a criança não pode viver com a sua família?", a:[{t:"O Estado deve garantir cuidados alternativos adequados, como famílias de acolhimento",ok:true},{t:"A criança fica automaticamente a cargo do Estado sem alternativas",ok:false},{t:"A criança perde os seus direitos enquanto não tiver família",ok:false}], exp:"O artigo 20.º garante que as crianças privadas do ambiente familiar têm direito a proteção e cuidados especiais — famílias de acolhimento, kafala ou, em último recurso, instituições adequadas." },
    { q:"O que é a adoção e que artigo da Convenção a regula?", a:[{t:"É um processo legal pelo qual uma criança passa a ser filho de outra família — artigo 21.º",ok:true},{t:"É um acordo informal entre famílias — sem base legal",ok:false},{t:"É proibida pela Convenção dos Direitos da Criança",ok:false}], exp:"O artigo 21.º regula a adoção, garantindo que é feita no superior interesse da criança. A adoção internacional deve respeitar tratados e evitar tráfico ou lucro indevido." },
    { q:"Qual é o princípio fundamental que deve orientar todas as decisões sobre crianças?", a:[{t:"O superior interesse da criança — artigo 3.º",ok:true},{t:"A vontade dos pais em primeiro lugar",ok:false},{t:"As leis económicas do país em questão",ok:false}], exp:"O artigo 3.º estabelece que o superior interesse da criança deve ser a consideração primordial em todas as decisões que a afetam. É o princípio-mestre da Convenção." }
  ],
  refugiados: [
    { q:"Qual artigo da Convenção protege especificamente as crianças refugiadas?", a:[{t:"Artigo 22.º",ok:true},{t:"Artigo 9.º",ok:false},{t:"Artigo 37.º",ok:false}], exp:"O artigo 22.º estabelece que as crianças que peçam o estatuto de refugiada ou sejam reconhecidas como tal têm direito a proteção especial e ao apoio dos Estados." },
    { q:"Quantas crianças estão deslocadas no mundo devido a conflitos e violência?", a:[{t:"Quase 49 milhões",ok:true},{t:"Menos de 1 milhão",ok:false},{t:"Cerca de 5 milhões",ok:false}], exp:"Segundo a UNICEF, quase 49 milhões de crianças vivem deslocadas por conflitos e violência em todo o mundo — a maior crise de deslocamento infantil desde a Segunda Guerra Mundial." },
    { q:"O que é o ACNUR?", a:[{t:"A agência das Nações Unidas para os refugiados",ok:true},{t:"Uma organização de países europeus para controlo de fronteiras",ok:false},{t:"Um programa de apoio alimentar da ONU",ok:false}], exp:"O ACNUR (Alto Comissariado das Nações Unidas para os Refugiados) protege refugiados, apátridas e pessoas deslocadas, trabalhando em mais de 130 países em parceria com a UNICEF." },
    { q:"Uma criança refugiada tem os mesmos direitos que as outras crianças?", a:[{t:"Sim, a Convenção aplica-se a todas as crianças sem discriminação",ok:true},{t:"Não, os refugiados têm direitos reduzidos",ok:false},{t:"Só se tiverem documentos de identidade válidos",ok:false}], exp:"O artigo 2.º afirma que todos os direitos se aplicam a todas as crianças, sem discriminação. Ser refugiado, apátrida ou migrante não reduz os direitos — pelo contrário, justifica proteção adicional." },
    { q:"O que é uma criança não acompanhada no contexto dos refugiados?", a:[{t:"Uma criança que atravessa fronteiras sem pais ou responsáveis legais",ok:true},{t:"Uma criança que viaja de avião sozinha",ok:false},{t:"Uma criança que não fala a língua do país de acolhimento",ok:false}], exp:"Crianças não acompanhadas ou separadas são especialmente vulneráveis a tráfico e abuso. O artigo 22.º exige que os Estados lhes deem a mesma proteção que a outras crianças, incluindo tutores." },
    { q:"Que direitos imediatos deve um país garantir a uma criança refugiada à chegada?", a:[{t:"Abrigo, alimentação, cuidados médicos e acesso à educação",ok:true},{t:"Apenas um visto temporário",ok:false},{t:"Só alojamento em centros de detenção",ok:false}], exp:"Independentemente do estatuto legal, uma criança refugiada tem direito imediato a condições de vida dignas, cuidados médicos e, o mais depressa possível, acesso à educação." }
  ],
  trabalho: [
    { q:"Qual é o artigo da Convenção que proíbe o trabalho infantil perigoso?", a:[{t:"Artigo 32.º",ok:true},{t:"Artigo 28.º",ok:false},{t:"Artigo 19.º",ok:false}], exp:"O artigo 32.º protege as crianças contra a exploração económica e qualquer trabalho perigoso, que prejudique a sua saúde ou interfira com a sua educação." },
    { q:"Quantas crianças trabalham em condições de exploração no mundo?", a:[{t:"Cerca de 138 milhões",ok:true},{t:"Menos de 10 milhões",ok:false},{t:"Cerca de 500 milhões",ok:false}], exp:"Segundo a OIT, cerca de 138 milhões de crianças estão em trabalho infantil, cerca de 54 milhões em formas perigosas. Este número tem vindo a descer nos últimos anos." },
    { q:"Qual é a idade mínima geral para trabalhar em Portugal?", a:[{t:"16 anos",ok:true},{t:"14 anos",ok:false},{t:"18 anos",ok:false}], exp:"Em Portugal, a idade mínima geral para trabalhar é 16 anos. Abaixo disso, só em situações muito específicas — como espetáculos culturais — e com autorização dos pais e das autoridades." },
    { q:"O que distingue o trabalho infantil perigoso de uma pequena ajuda em casa?", a:[{t:"O trabalho perigoso prejudica a saúde, a educação e o desenvolvimento da criança",ok:true},{t:"Qualquer trabalho feito por uma criança é automaticamente exploração",ok:false},{t:"Só é ilegal se a criança não receber salário",ok:false}], exp:"A OIT distingue entre trabalho aceitável — tarefas que não prejudicam o desenvolvimento — e trabalho infantil, que priva a criança da infância ou é perigoso para a saúde." },
    { q:"Em que setores é mais comum o trabalho infantil no mundo?", a:[{t:"Agricultura, minas, construção e trabalho doméstico",ok:true},{t:"Apenas nas fábricas têxteis da Ásia",ok:false},{t:"Só em países sem leis laborais",ok:false}], exp:"A maioria do trabalho infantil ocorre na agricultura (61%), seguida de serviços — como trabalho doméstico — e da indústria, incluindo minas e construção." },
    { q:"Qual organização internacional lidera o combate ao trabalho infantil a nível global?", a:[{t:"OIT — Organização Internacional do Trabalho",ok:true},{t:"INTERPOL",ok:false},{t:"Banco Mundial",ok:false}], exp:"A OIT define normas internacionais, como a Convenção n.º 182, que proíbe as piores formas de trabalho infantil e foi ratificada por todos os seus membros." }
  ],
  expressao: [
    { q:"Qual é o artigo da Convenção que garante a liberdade de expressão?", a:[{t:"Artigo 13.º",ok:true},{t:"Artigo 12.º",ok:false},{t:"Artigo 17.º",ok:false}], exp:"O artigo 13.º garante o direito de procurar, receber e transmitir informações e ideias — oralmente, por escrito, pela arte ou qualquer outro meio — desde que não prejudiquem os outros." },
    { q:"O artigo 17.º da Convenção trata de que direito?", a:[{t:"O acesso a informação e meios de comunicação adequados",ok:true},{t:"O direito a ter um telemóvel",ok:false},{t:"O direito a publicar um jornal escolar",ok:false}], exp:"O artigo 17.º encoraja os Estados a garantir que as crianças acedem a informação de fontes diversas, sobretudo material que promova o seu bem-estar social e moral." },
    { q:"O direito à liberdade de expressão tem limites?", a:[{t:"Sim, não pode ser usado para prejudicar os direitos e a reputação dos outros",ok:true},{t:"Não, é um direito absoluto sem qualquer restrição",ok:false},{t:"Sim, as crianças só podem expressar-se com autorização dos pais",ok:false}], exp:"O artigo 13.º reconhece que a liberdade de expressão pode ser limitada para proteger os direitos dos outros, a ordem pública, a saúde ou a moral." },
    { q:"O que é o bullying e como se relaciona com os direitos das crianças?", a:[{t:"É uma violação dos direitos da criança — prejudica a dignidade, a saúde e a educação",ok:true},{t:"É um problema menor que as crianças devem resolver sozinhas",ok:false},{t:"Só é relevante para os direitos se causar danos físicos",ok:false}], exp:"O bullying — físico, verbal ou online — viola vários artigos da Convenção: a dignidade, a proteção e a saúde. Escolas e Estados têm o dever de o prevenir e combater." },
    { q:"O que é a liberdade de pensamento e consciência das crianças? (art. 14.º)", a:[{t:"O direito a formar e expressar as suas próprias crenças e opiniões",ok:true},{t:"O direito a nunca frequentar aulas de religião",ok:false},{t:"O direito a não obedecer a regras escolares",ok:false}], exp:"O artigo 14.º garante a liberdade de pensamento, consciência e religião. Os pais podem orientar a criança nesta matéria, respeitando o seu superior interesse e autonomia crescente." },
    { q:"Como pode uma criança exercer o direito à expressão na escola?", a:[{t:"Participando em assembleias de turma, jornais escolares e projetos artísticos",ok:true},{t:"Apenas nos testes e fichas de avaliação",ok:false},{t:"Só se tiver autorização escrita dos pais",ok:false}], exp:"Assembleias de turma, conselhos de alunos, jornais escolares, teatro e projetos de cidadania são exemplos concretos do artigo 13.º no dia a dia escolar." }
  ],
  privacidade: [
    { q:"Qual é o artigo da Convenção que protege a privacidade das crianças?", a:[{t:"Artigo 16.º",ok:true},{t:"Artigo 8.º",ok:false},{t:"Artigo 13.º",ok:false}], exp:"O artigo 16.º garante que nenhuma criança seja sujeita a interferências arbitrárias na sua vida privada, família, domicílio ou correspondência, nem a ataques à sua honra." },
    { q:"O que é o RGPD e como protege as crianças?", a:[{t:"É o regulamento europeu de proteção de dados, que dá proteção especial aos dados de crianças",ok:true},{t:"É uma lei apenas para adultos",ok:false},{t:"É um sistema de controlo parental obrigatório",ok:false}], exp:"O RGPD, em vigor desde 2018, dá proteção especial aos dados pessoais das crianças. Em Portugal, o consentimento para usar dados de menores de 13 anos deve ser dado pelos pais." },
    { q:"As fotografias de crianças partilhadas sem autorização nas redes sociais violam algum direito?", a:[{t:"Sim, violam o direito à privacidade e à imagem da criança",ok:true},{t:"Não, qualquer pessoa pode partilhar fotos de crianças livremente",ok:false},{t:"Só é ilegal se a foto for em ambiente escolar",ok:false}], exp:"Partilhar fotos de crianças sem consentimento — mesmo de familiares — pode violar o direito à privacidade e à imagem, especialmente se as identificar." },
    { q:"O que devem as crianças fazer se sentirem que a sua privacidade está a ser violada online?", a:[{t:"Falar com um adulto de confiança e denunciar às plataformas ou autoridades",ok:true},{t:"Ignorar porque a internet não tem regras",ok:false},{t:"Responder ao agressor diretamente",ok:false}], exp:"O ideal é falar com um adulto de confiança e denunciar às plataformas digitais. Em Portugal, a Linha Internet Segura (1800 21 22 23) apoia quem passa por isto." },
    { q:"O que é o 'direito ao esquecimento' e como beneficia as crianças?", a:[{t:"O direito de pedir a remoção de informação pessoal online que já não é relevante",ok:true},{t:"O direito de não ser avaliado na escola",ok:false},{t:"O direito de apagar as notas negativas do boletim escolar",ok:false}], exp:"O 'direito ao esquecimento' (RGPD, art. 17.º) permite pedir a remoção de dados pessoais. É especialmente importante para os jovens: publicações de infância não devem persegui-los na vida adulta." },
    { q:"O que é o 'sharenting' e que riscos apresenta?", a:[{t:"É a partilha excessiva de fotos e dados de filhos pelos pais nas redes sociais",ok:true},{t:"É um tipo de bullying online entre crianças",ok:false},{t:"É um sistema de controlo parental digital",ok:false}], exp:"'Sharenting' é a prática de partilhar publicações frequentes sobre os filhos online. Pode violar a privacidade da criança e criar uma 'pegada digital' sem o seu consentimento." }
  ],
  cultura: [
    { q:"Qual artigo garante às crianças de minorias o direito à sua língua e cultura?", a:[{t:"Artigo 30.º",ok:true},{t:"Artigo 17.º",ok:false},{t:"Artigo 28.º",ok:false}], exp:"O artigo 30.º estabelece que as crianças de minorias étnicas, religiosas ou linguísticas não podem ser privadas do direito à sua cultura, à sua religião ou à sua língua." },
    { q:"O que é a diversidade cultural e por que é importante respeitar?", a:[{t:"É a variedade de culturas, línguas e tradições no mundo — enriquece a humanidade",ok:true},{t:"É um problema que dificulta a convivência entre povos",ok:false},{t:"Só é relevante fora de Portugal",ok:false}], exp:"A UNESCO defende que todas as culturas têm o mesmo valor e merecem proteção. Em Portugal vivem pessoas de mais de 180 nacionalidades diferentes." },
    { q:"Quantas línguas são faladas no mundo atualmente?", a:[{t:"Cerca de 7 000 línguas",ok:true},{t:"Cerca de 200 línguas",ok:false},{t:"Cerca de 1 000 línguas",ok:false}], exp:"Estima-se que existam cerca de 7 000 línguas vivas no mundo. Muitas estão em risco de extinção — preservar as línguas minoritárias é proteger a diversidade cultural." },
    { q:"Em Portugal, que língua além do Português tem estatuto oficial de língua regional?", a:[{t:"O Mirandês, falado em Miranda do Douro",ok:true},{t:"O Galego, falado no Norte",ok:false},{t:"O Crioulo, falado em Lisboa",ok:false}], exp:"O Mirandês é a única língua regional com reconhecimento oficial em Portugal, falada em Miranda do Douro. Tem raízes na antiga língua asturo-leonesa e é património linguístico único." },
    { q:"O que é a UNESCO e que papel tem na proteção das culturas?", a:[{t:"É a agência da ONU para a educação, ciência e cultura — protege o património cultural mundial",ok:true},{t:"É uma organização de países ricos para financiar museus",ok:false},{t:"É o serviço secreto cultural da União Europeia",ok:false}], exp:"A UNESCO promove a paz através da educação, da ciência e da cultura, gerindo a Lista do Património Mundial e protegendo tradições, línguas e expressões culturais." },
    { q:"Porque é importante que as crianças conheçam a cultura dos outros?", a:[{t:"Para desenvolver empatia, respeito e competências para viver num mundo diverso",ok:true},{t:"Para poder criticar melhor as outras culturas",ok:false},{t:"Porque a lei obriga ao estudo de todas as culturas",ok:false}], exp:"O contacto com outras culturas desde cedo desenvolve empatia e prepara para uma cidadania global. O artigo 29.º destaca o respeito pelas outras culturas como objetivo da educação." }
  ],
  deficiencia: [
    { q:"Qual artigo da Convenção protege as crianças com deficiência?", a:[{t:"Artigo 23.º",ok:true},{t:"Artigo 24.º",ok:false},{t:"Artigo 28.º",ok:false}], exp:"O artigo 23.º reconhece que as crianças com deficiência têm direito a uma vida plena e digna, com participação ativa na sociedade e apoio especial dos Estados." },
    { q:"O que é a educação inclusiva?", a:[{t:"Um sistema em que todas as crianças, com ou sem deficiência, aprendem juntas",ok:true},{t:"Um sistema de escolas separadas para crianças com necessidades especiais",ok:false},{t:"Aulas online para crianças com mobilidade reduzida",ok:false}], exp:"A educação inclusiva pressupõe que todas as crianças aprendam juntas, com as adaptações necessárias. Portugal tem avançado neste modelo, com apoio especializado nas escolas regulares." },
    { q:"Qual a percentagem estimada de crianças no mundo com algum tipo de deficiência?", a:[{t:"Cerca de 15%",ok:true},{t:"Menos de 1%",ok:false},{t:"Mais de 50%",ok:false}], exp:"A OMS estima que cerca de 15% da população mundial vive com alguma forma de deficiência. Muitas crianças ainda enfrentam barreiras no acesso à educação, à saúde e à participação social." },
    { q:"O que são tecnologias de apoio e como ajudam as crianças com deficiência?", a:[{t:"São ferramentas que compensam limitações e aumentam a autonomia e participação",ok:true},{t:"São medicamentos especiais para crianças com deficiência",ok:false},{t:"São apenas cadeiras de rodas e bengalas",ok:false}], exp:"Incluem software de leitura de ecrã, comunicadores alternativos e impressoras Braille — permitem que crianças com deficiências físicas, sensoriais ou cognitivas participem plenamente na escola." },
    { q:"O que é a acessibilidade e por que é um direito das crianças com deficiência?", a:[{t:"É a garantia de que espaços, serviços e informação são utilizáveis por todos",ok:true},{t:"É um benefício opcional que os países podem oferecer",ok:false},{t:"É apenas sobre rampas para cadeiras de rodas",ok:false}], exp:"A acessibilidade — física, digital e comunicacional — é condição para as crianças com deficiência exercerem os seus direitos. O artigo 23.º exige que os Estados removam barreiras." },
    { q:"O que significa o slogan 'Nada sobre nós sem nós' no contexto das crianças com deficiência?", a:[{t:"Que as decisões que as afetam devem contar com a sua participação",ok:true},{t:"Que as crianças com deficiência devem viver de forma completamente independente",ok:false},{t:"Que os pais não devem participar nas decisões sobre os filhos",ok:false}], exp:"É o lema do movimento de defesa dos direitos das pessoas com deficiência: qualquer política que as afete deve ser desenvolvida com a sua participação ativa." }
  ],
  ambiente: [
    { q:"Existe um artigo específico sobre o direito ao ambiente na Convenção de 1989?", a:[{t:"Não diretamente, mas os ODS e comentários gerais reconhecem este direito",ok:true},{t:"Sim, é o artigo 29.º",ok:false},{t:"Sim, foi acrescentado em 2010",ok:false}], exp:"A Convenção de 1989 não tem um artigo próprio sobre ambiente, mas o Comité dos Direitos da Criança reconhece que as alterações climáticas ameaçam todos os direitos das crianças." },
    { q:"Como afetam as alterações climáticas os direitos das crianças?", a:[{t:"Ameaçam o direito à saúde, à alimentação, à água e a um futuro seguro",ok:true},{t:"Não afetam significativamente as crianças",ok:false},{t:"Só afetam crianças que vivem em zonas costeiras",ok:false}], exp:"Aumentam doenças respiratórias, reduzem o acesso a água e alimentos e causam deslocamentos forçados. A UNICEF alerta que mais de mil milhões de crianças vivem em zonas de risco extremo." },
    { q:"O que pode cada criança fazer para ajudar o ambiente?", a:[{t:"Reduzir desperdícios, poupar energia, plantar árvores e sensibilizar outros",ok:true},{t:"Nada — só os governos e empresas podem fazer diferença",ok:false},{t:"Deixar de ir à escola para protestar",ok:false}], exp:"Separar o lixo, poupar água e energia, escolher produtos sustentáveis e sensibilizar família e amigos. As pequenas ações, multiplicadas por milhões, fazem diferença." },
    { q:"O que significa a sigla ODS?", a:[{t:"Objetivos de Desenvolvimento Sustentável",ok:true},{t:"Organização dos Direitos Sociais",ok:false},{t:"Ordem de Defesa da Sustentabilidade",ok:false}], exp:"Os ODS são 17 metas aprovadas pela ONU em 2015 para tornar o mundo melhor até 2030. Os ODS 13, 14 e 15 protegem diretamente o ambiente onde as crianças crescem." },
    { q:"O que é a 'pegada ecológica'?", a:[{t:"A quantidade de recursos naturais que cada pessoa consome",ok:true},{t:"O rasto de sujidade que deixamos no chão",ok:false},{t:"O número de animais que existem numa floresta",ok:false}], exp:"Mede os recursos naturais — água, terra, energia — que cada pessoa usa. Se toda a humanidade vivesse como um europeu médio, precisaríamos de 3 planetas!" },
    { q:"Qual é o principal gás responsável pelo aquecimento global?", a:[{t:"O dióxido de carbono (CO₂)",ok:true},{t:"O oxigénio (O₂)",ok:false},{t:"O azoto (N₂)",ok:false}], exp:"O CO₂, libertado pela queima de combustíveis fósseis, é o principal responsável pelo efeito de estufa. As florestas absorvem CO₂ — por isso a desflorestação agrava o problema." },
    { q:"O que é a biodiversidade e por que é importante para as crianças?", a:[{t:"É a variedade de seres vivos no planeta, essencial para o equilíbrio da natureza",ok:true},{t:"É um tipo de energia renovável produzida por animais",ok:false},{t:"É o nome científico das florestas tropicais",ok:false}], exp:"Sem biodiversidade perderíamos alimentos, medicamentos e o equilíbrio dos ecossistemas — as crianças de hoje herdarão um planeta mais pobre se não agirmos." }
  ],
  digital: [
    { q:"Os direitos das crianças aplicam-se também ao mundo online?", a:[{t:"Sim, todos os direitos da Convenção se aplicam ao espaço digital",ok:true},{t:"Não, a internet é um espaço sem regras para crianças",ok:false},{t:"Só a partir dos 16 anos os direitos digitais são reconhecidos",ok:false}], exp:"Em 2021, o Comité dos Direitos da Criança da ONU confirmou que todos os direitos da Convenção se aplicam ao ambiente digital — privacidade, proteção, expressão e educação incluídas." },
    { q:"O que é o ciberbullying e como se combate?", a:[{t:"É assédio ou intimidação online — combate-se com educação, denúncia e apoio",ok:true},{t:"É um jogo de computador perigoso",ok:false},{t:"Só acontece em redes sociais e não é muito grave",ok:false}], exp:"É o assédio ou a ameaça através de meios digitais, e pode causar ansiedade e isolamento. Em Portugal, a Linha Internet Segura (1800 21 22 23) apoia vítimas." },
    { q:"Que cuidados deve ter uma criança ao usar redes sociais?", a:[{t:"Não partilhar dados pessoais, ter perfil privado e contar a um adulto se algo correr mal",ok:true},{t:"Aceitar todos os pedidos de amizade para ter mais seguidores",ok:false},{t:"Partilhar a localização para que os amigos saibam onde está",ok:false}], exp:"Perfil privado, não partilhar morada ou escola, não aceitar pedidos de estranhos e contar sempre a um adulto se algo parecer errado." },
    { q:"Qual é a idade mínima para criar conta nas principais redes sociais?", a:[{t:"13 anos na maioria das plataformas (Instagram, TikTok, YouTube)",ok:true},{t:"10 anos, com autorização dos pais",ok:false},{t:"18 anos em todas as plataformas",ok:false}], exp:"A maioria das grandes plataformas exige 13 anos, com base na lei norte-americana COPPA. Na UE, o RGPD fixa os 16 anos como regra geral, mas Portugal baixou para 13." },
    { q:"O que é a literacia digital?", a:[{t:"A capacidade de usar a tecnologia de forma segura, crítica e responsável",ok:true},{t:"Saber escrever código de programação",ok:false},{t:"Ter muitos seguidores nas redes sociais",ok:false}], exp:"É o conjunto de competências que permitem usar a internet de forma segura e crítica: distinguir informação verdadeira de falsa e proteger os dados pessoais." },
    { q:"O que é o phishing e como se protege uma criança?", a:[{t:"É uma tentativa de enganar para obter dados pessoais — não clicar em links suspeitos",ok:true},{t:"É um jogo de pesca online muito popular",ok:false},{t:"É um vírus que apaga os ficheiros do computador",ok:false}], exp:"É quando alguém finge ser uma entidade de confiança para roubar palavras-passe. A proteção passa por não clicar em links suspeitos e avisar sempre um adulto." },
    { q:"O que são 'fake news' e como podemos identificá-las?", a:[{t:"São notícias falsas — verifica a fonte, a data e procura outras referências",ok:true},{t:"São notícias sobre acontecimentos futuros",ok:false},{t:"São notícias publicadas apenas nas redes sociais",ok:false}], exp:"São notícias falsas ou enganosas. Para as identificar: verifica se a fonte é credível, procura a mesma notícia noutros meios e desconfia de títulos muito chocantes." },
    { q:"Qual linha de apoio podes contactar em Portugal se tiveres um problema online?", a:[{t:"Linha Internet Segura: 1800 21 22 23",ok:true},{t:"Linha de Apoio à Vítima: 116 006",ok:false},{t:"Linha de Saúde: 808 24 24 24",ok:false}], exp:"A Linha Internet Segura é gratuita e apoia crianças e jovens com ciberbullying, conteúdos perturbadores ou outros problemas online. Podes também denunciar em www.internetsegura.pt." }
  ]
};
